# Generated by Django 4.2.27 on 2025-12-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_options_remove_auditlog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
