# Generated by Django 4.2.27 on 2025-12-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_hash_auditlog_previous_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='company_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
