# Generated by Django 4.2.27 on 2025-12-18 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0002_employee_reporting_to_alter_employee_employee_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Numeric target value (e.g. 10000 sales)', max_digits=10)),
                ('unit', models.CharField(blank=True, help_text='e.g. USD, Units, Percentage', max_length=50)),
                ('weightage', models.IntegerField(default=1, help_text='Importance weight (1-10)')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_designation', models.CharField(max_length=255)),
                ('new_designation', models.CharField(max_length=255)),
                ('promotion_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('period_name', models.CharField(help_text='e.g. Annual 2024, Q1 2025', max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Needs Improvement'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employees.employee')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Increment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('increment_date', models.DateField()),
                ('increment_amount', models.DecimalField(decimal_places=2, help_text='Difference', max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='% Increase', max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('assigned_target', models.DecimalField(blank=True, decimal_places=2, help_text='Override standard target if needed', max_digits=10, null=True)),
                ('achieved_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated score', max_digits=5, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='employees.employee')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.kpi')),
            ],
            options={
                'unique_together': {('employee', 'kpi', 'period_start')},
            },
        ),
    ]
