# Generated by Django 4.2.27 on 2026-01-08 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0010_customer_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_uuid', models.UUIDField(blank=True, db_index=True, help_text='Reference to Employee in HRMS', null=True)),
                ('balance', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Loyalty', max_length=255)),
                ('earn_rate', models.DecimalField(decimal_places=2, default=0.1, help_text='Points earned per currency unit (e.g. 0.1 = 1 point per $10)', max_digits=5)),
                ('redemption_rate', models.DecimalField(decimal_places=2, default=0.01, help_text='Currency value per point (e.g. 0.01 = 1 cent per point)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('target_audience', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee')], default='customer', max_length=20)),
                ('company_uuid', models.UUIDField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('expire', 'Expired'), ('adjust', 'Adjustment')], max_length=20)),
                ('points', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_id', models.CharField(blank=True, help_text='Order UUID or external ref', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_points', models.IntegerField(help_text='Lifetime points required to reach this tier')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Point earning multiplier', max_digits=4)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='loyalty.loyaltyprogram')),
            ],
            options={
                'ordering': ['min_points'],
            },
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='current_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.loyaltytier'),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to='profiles.customer'),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loyalty.loyaltyprogram'),
        ),
    ]
