# Generated by Django 4.2.27 on 2025-12-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='geo_location',
            field=models.JSONField(blank=True, help_text="{'lat': 0.0, 'lng': 0.0}", null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='proof_of_delivery',
            field=models.ImageField(blank=True, null=True, upload_to='pod/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
