# Generated by Django 4.2.27 on 2026-01-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shipment_delivered_at_shipment_delivery_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroute',
            name='branch_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryroute',
            name='company_uuid',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='branch_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='company_uuid',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='branch_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='company_uuid',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('FAILED', 'Delivery Failed')], default='PENDING', max_length=20),
        ),
    ]
