-- ================================================
-- Adaptix Single Database Schema Initialization
-- ================================================
-- Creates separate schemas for each service
-- Provides isolation while sharing one database

-- Create schemas for each service
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS company;
CREATE SCHEMA IF NOT EXISTS product;
CREATE SCHEMA IF NOT EXISTS pos;
CREATE SCHEMA IF NOT EXISTS inventory;
CREATE SCHEMA IF NOT EXISTS purchase;
CREATE SCHEMA IF NOT EXISTS hrms;
CREATE SCHEMA IF NOT EXISTS accounting;
CREATE SCHEMA IF NOT EXISTS customer;
CREATE SCHEMA IF NOT EXISTS asset;
CREATE SCHEMA IF NOT EXISTS promotion;
CREATE SCHEMA IF NOT EXISTS payment;
CREATE SCHEMA IF NOT EXISTS notification;
CREATE SCHEMA IF NOT EXISTS reporting;
CREATE SCHEMA IF NOT EXISTS manufacturing;
CREATE SCHEMA IF NOT EXISTS quality;
CREATE SCHEMA IF NOT EXISTS logistics;
CREATE SCHEMA IF NOT EXISTS intelligence;

-- Grant privileges to adaptix user
GRANT ALL PRIVILEGES ON SCHEMA auth TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA company TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA product TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA pos TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA inventory TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA purchase TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA hrms TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA accounting TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA customer TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA asset TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA promotion TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA payment TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA notification TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA reporting TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA manufacturing TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA quality TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA logistics TO adaptix;
GRANT ALL PRIVILEGES ON SCHEMA intelligence TO adaptix;

-- Allow creating tables in schemas
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA company TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA product TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA pos TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA inventory TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA purchase TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hrms TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA accounting TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA customer TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA asset TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA promotion TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA payment TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA notification TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA reporting TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA manufacturing TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA quality TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA logistics TO adaptix;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA intelligence TO adaptix;

-- Set default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA company GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA product GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA pos GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA purchase GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA hrms GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA accounting GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA customer GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA asset GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA promotion GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA payment GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA manufacturing GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA quality GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA logistics GRANT ALL PRIVILEGES ON TABLES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA intelligence GRANT ALL PRIVILEGES ON TABLES TO adaptix;

-- Grant sequence privileges
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA company GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA product GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA pos GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA purchase GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA hrms GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA accounting GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA customer GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA asset GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA promotion GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA payment GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA manufacturing GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA quality GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA logistics GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;
ALTER DEFAULT PRIVILEGES IN SCHEMA intelligence GRANT ALL PRIVILEGES ON SEQUENCES TO adaptix;

-- Log success
DO $$
BEGIN
    RAISE NOTICE 'All schemas created successfully!';
END $$;
