# Generated by Django 4.2 on 2025-12-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_accountgroup_remove_employee_external_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('fmcg', 'FMCG (Dairy, Bakery, Grocery, Fish/Meat)'), ('food_expo', 'Food Expo (Restaurant, Fast Food)'), ('coffee_tea', 'Coffee & Tea Corner'), ('fashion', 'FitFat (Fashion - RMG)'), ('clothing', 'Clothing (Fabrics, Home Tex)'), ('tailor', "Tailor's Shop"), ('laundry', 'Laundry Shop'), ('luggage', 'CarryOne (Luggage & Baggage)'), ('sports', 'Toss (Sports, Kids Zone)'), ('pharmacy', 'PharmaTech (Medicine)'), ('eyewear', 'LensLine (Eyeware)'), ('healthcare', 'Day Care / Doctor Point'), ('beauty_spa', 'Beauty Care (Spa & Saloon)'), ('footwear', 'Footwear Shop'), ('electronics', 'Electronics Products'), ('it_mobile', 'IT and Mobile Phone'), ('automotive', 'Torque Automobiles'), ('hardware', 'Lock & Hook (Hardware)'), ('furniture', 'Joratali (Furniture)'), ('jewelry', 'Gold Stone (Jewelry)'), ('blacksmith', 'Black Smith'), ('stationery', 'Clips (Books & Stationery)'), ('legal', 'Law Firm'), ('matrimonial', 'KajerKazi (Matrimonial)'), ('freelancing', 'Freelancing Studio'), ('studio', 'Aloadhari (Studio)'), ('design_house', 'ThemeSketch (Design House)'), ('construction', 'SandsBricks (Construction)'), ('customer_service', 'ThikThak (Customer Service)'), ('convention_hall', 'Convention Hall'), ('parking', 'Parking'), ('funeral', 'Funeral Shop'), ('pet_shop', 'Pet Shop'), ('finance', 'Finance and Banking'), ('toys', 'Toys Shop'), ('helipad', 'Helipad'), ('agro', 'Agro and Plantation'), ('courier', 'Courier Service'), ('entertainment', 'Theatre and Cineplex')], default='fmcg', max_length=50),
        ),
    ]
