# Generated by Django 4.2 on 2025-12-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_opt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryoptimization',
            options={'verbose_name_plural': 'Inventory Optimizations'},
        ),
        migrations.RemoveIndex(
            model_name='inventoryoptimization',
            name='inventory_o_product_32e237_idx',
        ),
        migrations.AddField(
            model_name='inventoryoptimization',
            name='company_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoptimization',
            name='estimated_stockout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryoptimization',
            name='stockout_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='inventoryoptimization',
            index=models.Index(fields=['company_uuid', 'product_uuid', 'branch_id'], name='inventory_o_company_914f31_idx'),
        ),
    ]
