# Generated by Django 4.2 on 2026-01-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_opt', '0002_alter_inventoryoptimization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoptimization',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
