# Generated by Django 4.2.27 on 2025-12-23 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        ('employees', '0003_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branch_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Specific Branch/Subsidiary UUID', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='shifts.shift'),
        ),
    ]
