# Generated by Django 4.2.27 on 2025-12-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_branch_uuid_employee_current_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_policy',
            field=models.CharField(choices=[('STRICT', 'Strict (Shift Based)'), ('FLEXIBLE', 'Flexible (One Punch)'), ('NONE', 'No Tracking')], default='STRICT', help_text='Determines how late/early status is calculated.', max_length=20),
        ),
    ]
