# Generated by Django 4.2.27 on 2025-12-27 04:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('procurement', '0002_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_uuid', models.UUIDField(db_index=True)),
                ('variant_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('converted', 'Converted to PO'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_lead_time_days', models.PositiveIntegerField(help_text='Days to deliver')),
                ('valid_until', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_winning_quote', models.BooleanField(default=False)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='procurement.rfq')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='vendors.vendor')),
            ],
            options={
                'unique_together': {('rfq', 'vendor', 'company_uuid')},
            },
        ),
        migrations.AddField(
            model_name='rfq',
            name='selected_quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_rfq', to='procurement.vendorquote'),
        ),
    ]
