# Generated by Django 4.2.27 on 2025-12-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_rfq_vendorquote_rfq_selected_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
