# Generated by Django 4.2.27 on 2026-01-04 05:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_purchaseorder_branch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcurementSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('product_uuid', models.UUIDField(db_index=True)),
                ('suggested_quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('estimated_out_of_stock_date', models.DateField()),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='AI confidence (0.0 - 1.0)', max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('reasoning', models.TextField(blank=True, help_text='Why was this suggested? (e.g. Sales trend up 20%)', null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('linked_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ['-confidence_score', 'estimated_out_of_stock_date'],
            },
        ),
    ]
