# Generated by Django 4.2.27 on 2025-12-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_possession_order_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
