# Generated by Django 4.2.27 on 2025-12-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_order_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_zone_code',
            field=models.CharField(blank=True, help_text='Code of the tax zone for this order', max_length=50, null=True),
        ),
    ]
