# Generated by manual addition

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_order_tax_zone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, help_text='Bank or Mobile Banking provider (e.g. Bkash, Nagad, Brac Bank)', max_length=100, null=True),
        ),
    ]
