# Generated by Django 4.2.27 on 2025-12-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_orderreturn_possettings_alter_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='emi_plan',
            field=models.UUIDField(blank=True, help_text='ID of the EMI plan if method is emi', null=True),
        ),
    ]
