# Generated by Django 4.2 on 2026-01-04 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('asset_id', models.UUIDField(db_index=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.IntegerField(default=0, help_text='0-100 risk of failure')),
                ('failure_probability', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('estimated_remaining_life_weeks', models.IntegerField(blank=True, null=True)),
                ('anomaly_type', models.CharField(blank=True, max_length=50)),
                ('reasoning', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('maintenance_task_id', models.UUIDField(blank=True, help_text='Linked task in Asset service', null=True)),
            ],
            options={
                'verbose_name_plural': 'Maintenance Anomalies',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
