import logging
from django.utils import timezone
from .models import LeavePolicy, LeaveAllocation, LeaveType
from apps.employees.models import Employee
from decimal import Decimal

logger = logging.getLogger(__name__)

class EntitlementEngine:
    """
    Core engine to calculate and generate leave allocations based on policies.
    """
    
    @staticmethod
    def calculate_tenure_months(joining_date):
        if not joining_date:
            return 0
        today = timezone.now().date()
        return (today.year - joining_date.year) * 12 + today.month - joining_date.month

    @staticmethod
    def run_entitlement_for_company(company_uuid):
        """
        Runs the entitlement calculation for all employees in a company.
        """
        policies = LeavePolicy.objects.filter(company_uuid=company_uuid, is_active=True)
        employees = Employee.objects.filter(company_uuid=company_uuid, is_active=True)
        
        allocations_created = 0
        current_year = timezone.now().year
        
        for employee in employees:
            tenure_months = EntitlementEngine.calculate_tenure_months(employee.joining_date)
            
            for policy in policies:
                # 1. Check Tenure Requirement
                if tenure_months < policy.tenure_months_required:
                    continue
                
                # 2. Check Gender Requirement
                if policy.gender_requirement != 'ALL' and employee.gender != policy.gender_requirement:
                    continue
                    
                # 3. Check for existing allocation for this year
                existing = LeaveAllocation.objects.filter(
                    employee=employee,
                    leave_type=policy.leave_type,
                    year=current_year
                ).exists()
                
                if not existing:
                    LeaveAllocation.objects.create(
                        company_uuid=company_uuid,
                        employee=employee,
                        leave_type=policy.leave_type,
                        year=current_year,
                        total_allocated=policy.allocation_days,
                        status='DRAFT',
                        notes=f"Auto-generated by Policy: {policy.name}"
                    )
                    allocations_created += 1
                    
        return allocations_created
