# Generated by Django 4.2 on 2025-12-23 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_company_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Is this a Group/Holding Company?'),
        ),
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='tenants.company'),
        ),
    ]
