# Generated by Django 4.2 on 2025-12-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_company_is_group_company_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='auth_company_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
