# Generated by Django 4.2 on 2025-12-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_company_auth_company_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='entity_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('FACTORY', 'Factory'), ('STORE', 'Store'), ('WAREHOUSE', 'Warehouse')], default='GENERAL', max_length=20),
        ),
    ]
