# Generated by Django 4.2 on 2025-12-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_company_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='smtp_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Tenant-specific SMTP: host, port, user, password, from_email'),
        ),
        migrations.AddField(
            model_name='companysetting',
            name='theme_config',
            field=models.JSONField(blank=True, default=dict, help_text='Extended theming: font, radius, etc.'),
        ),
    ]
