# Generated by Django 4.2 on 2025-12-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_company_custom_domain_companysetting_smtp_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wing',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wing',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='entity_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('FACTORY', 'Factory'), ('STORE', 'Store'), ('WAREHOUSE', 'Warehouse'), ('ECOMMERCE', 'Ecommerce')], default='GENERAL', max_length=20),
        ),
    ]
