# Generated by Django 4.2.27 on 2025-12-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='device_data',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='longitude',
        ),
        migrations.AddField(
            model_name='attendance',
            name='early_out_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_flexible',
            field=models.BooleanField(default=False, help_text='Copied from employee policy at time of punch'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
