# Generated by Django 4.2.27 on 2025-12-21 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
