# Generated by Django 4.2.27 on 2026-01-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0003_operation_productionorderoperation_bomoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='target_warehouse_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
