# Generated by Django 4.2.27 on 2026-01-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0004_productionorder_target_warehouse_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='source_order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='source_order_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorderoperation',
            name='assigned_worker_uuids',
            field=models.JSONField(blank=True, default=list, help_text='List of worker UUIDs assigned (HRMS)'),
        ),
    ]
