# Generated by Django 4.2.27 on 2026-01-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0005_productionorder_source_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='qc_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('QUALITY_CHECK', 'Quality Check'), ('REWORK', 'Rework'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
