# Generated by Django 4.2.27 on 2026-01-04 05:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0006_productionorder_qc_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('product_uuid', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('PRODUCTION', 'In Production'), ('QC', 'Quality Check'), ('INVENTORY', 'In Inventory'), ('RESERVED', 'Reserved'), ('SHIPPED', 'Shipped'), ('REWORK', 'Rework')], default='PRODUCTION', max_length=20)),
                ('qr_code_data', models.TextField(blank=True)),
                ('current_warehouse_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reservation_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('qc_history', models.JSONField(blank=True, default=list)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='mrp.productionorder')),
            ],
        ),
    ]
