# Generated by Django 4.2.27 on 2026-01-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0008_productunit_color_productunit_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
