# Generated by Django 4.2.27 on 2026-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0009_alter_operation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcenter',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
