# Generated by Django 4.2.27 on 2026-01-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0010_alter_workcenter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
