# Generated by Django 4.2.27 on 2025-12-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_accounting_codes_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direct_permissions',
            field=models.ManyToManyField(blank=True, related_name='users_direct', to='accounts.permission'),
        ),
    ]
