# Generated by Django 4.2.27 on 2025-12-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_direct_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
