# Generated by Django 4.2.27 on 2025-12-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_custom_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Link to Company Service Wing UUID (Branch)', null=True),
        ),
    ]
