# Generated by Django 4.2.27 on 2025-12-24 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('account_payable', models.UUIDField(blank=True, help_text='UUID of Liability Account (Output Tax)', null=True)),
                ('account_receivable', models.UUIDField(blank=True, help_text='UUID of Asset Account (Input Tax)', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='e.g. BD, SA, NY', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('product_category_uuid', models.UUIDField(blank=True, help_text='Apply only to this category', null=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Higher priority rules override lower ones')),
                ('is_active', models.BooleanField(default=True)),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax.tax')),
                ('tax_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='tax.taxzone')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
