# Generated by Django 4.2.27 on 2026-01-04 06:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Celsius', max_digits=6, null=True)),
                ('vibration', models.DecimalField(blank=True, decimal_places=2, help_text='G-force/mm/s', max_digits=6, null=True)),
                ('power_usage', models.DecimalField(blank=True, decimal_places=2, help_text='Watts/kWh', max_digits=10, null=True)),
                ('usage_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Cumulative hours', max_digits=10, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='assets.asset')),
            ],
            options={
                'verbose_name_plural': 'Asset Telemetry',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenanceTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('task_type', models.CharField(choices=[('routine', 'Routine'), ('repair', 'Repair'), ('preventive', 'Preventive (AI)'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('suggested_date', models.DateField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='assets.asset')),
            ],
        ),
    ]
