# Generated by Django 4.2.27 on 2026-01-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assettelemetry_assetmaintenancetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location_type',
            field=models.CharField(choices=[('factory', 'Factory'), ('branch', 'Branch'), ('headoffice', 'Head Office'), ('corporate', 'Corporate')], default='headoffice', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='wing_uuid',
            field=models.UUIDField(blank=True, help_text='Branch/Unit UUID from Company Service', null=True),
        ),
    ]
