from django.db import models
from apps.utils.models import SoftDeleteModel

class SalesHistory(SoftDeleteModel):
    """
    Aggregated daily sales data per product.
    Synced from POS service daily.
    """
    product_uuid = models.UUIDField(db_index=True)
    product_name = models.CharField(max_length=255)
    category = models.CharField(max_length=100, blank=True, null=True)
    
    date = models.DateField(db_index=True)
    
    quantity_sold = models.DecimalField(max_digits=12, decimal_places=3, default=0)
    revenue = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    
    company_uuid = models.UUIDField(db_index=True)
    
    class Meta:
        unique_together = ('product_uuid', 'date', 'company_uuid')
        indexes = [
            models.Index(fields=['company_uuid', 'date']),
        ]

    def __str__(self):
        return f"{self.product_name} - {self.date}: {self.quantity_sold}"

class Forecast(SoftDeleteModel):
    """
    Predicted demand for a product for a specific future date.
    Generated by the Forecasting Engine.
    """
    product_uuid = models.UUIDField(db_index=True)
    product_name = models.CharField(max_length=255)
    
    forecast_date = models.DateField(db_index=True)
    
    predicted_quantity = models.DecimalField(max_digits=12, decimal_places=3)
    confidence_score = models.FloatField(default=0.0) # 0.0 to 1.0
    
    algorithm_used = models.CharField(max_length=50, default='simple_moving_average')
    
    company_uuid = models.UUIDField(db_index=True)
    
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('product_uuid', 'forecast_date', 'company_uuid')

    def __str__(self):
        return f"Forecast {self.product_name} - {self.forecast_date}: {self.predicted_quantity}"
