# Generated by Django 4.2 on 2026-01-04 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('journal_entry_id', models.UUIDField(db_index=True)),
                ('journal_date', models.DateField()),
                ('journal_reference', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('anomaly_type', models.CharField(choices=[('statistical_outlier', 'Statistical Outlier'), ('duplicate_entry', 'Duplicate Entry'), ('round_number', 'High Round Number'), ('unusual_velocity', 'Unusual Velocity'), ('unmatched_entry', 'Unmatched/Suspicious Entry')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('reasoning', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Financial Anomalies',
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
    ]
