# Generated by Django 4.2 on 2026-01-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_anomalies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialanomaly',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
