# Generated by Django 4.2 on 2026-01-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_anomalies', '0002_alter_financialanomaly_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialanomaly',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
    ]
