# Generated by Django 4.2.27 on 2025-12-11 04:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_reporting_to_alter_employee_employee_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_time_in', models.PositiveIntegerField(default=15, help_text='Minutes allowed after start_time before marked late')),
                ('grace_time_out', models.PositiveIntegerField(default=0, help_text='Minutes allowed before end_time (early leave)')),
                ('is_overnight', models.BooleanField(default=False, help_text='If True, shift ends on the next day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('company_uuid', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, db_index=True, help_text='If null, indefinitely assigned', null=True)),
                ('assigned_by', models.UUIDField(blank=True, help_text='User UUID of supervisor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='employees.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='shifts.shift')),
            ],
            options={
                'indexes': [models.Index(fields=['company_uuid', 'start_date', 'end_date'], name='shifts_empl_company_f88283_idx'), models.Index(fields=['employee', 'start_date'], name='shifts_empl_employe_2fa9fd_idx')],
            },
        ),
    ]
