# Generated by Django 4.2.27 on 2025-12-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='branch_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('FACTORY', 'Factory'), ('STORE', 'Store'), ('WAREHOUSE', 'Warehouse')], default='GENERAL', max_length=20),
        ),
    ]
