# Generated by Django 4.2.27 on 2025-12-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shift_branch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshift',
            name='company_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='company_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
