# Generated by Django 4.2.27 on 2025-12-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posted_by',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
