# Generated by Django 4.2.27 on 2025-12-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_journalentry_is_posted_alter_journalentry_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccount',
            unique_together={('company_uuid', 'code')},
        ),
    ]
