# Generated by Django 4.2.27 on 2026-01-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_chartofaccount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='wing_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
