# Generated by Django 4.2.27 on 2025-12-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_customer_email_otp_customer_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_email_verified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_phone_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
