# Generated by Django 4.2.27 on 2025-12-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='branch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='attributeset',
            name='branch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='branch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
