# Generated by Django 4.2.27 on 2025-12-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_attribute_branch_id_attributeset_branch_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_active_customer_phone',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('company_uuid', 'phone'), name='unique_active_customer_phone'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('email__isnull', False)), fields=('company_uuid', 'email'), name='unique_active_customer_email'),
        ),
    ]
