# Generated by Django 4.2.27 on 2026-01-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_customer_unique_active_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price_list_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
