# Generated by Django 4.2.27 on 2026-01-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_customer_price_list_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Link to Auth Service User UUID', null=True),
        ),
    ]
