# Generated by Django 4.2.27 on 2025-12-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_type_product_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='return_window_days',
            field=models.IntegerField(default=30, help_text='Number of days eligible for return'),
        ),
    ]
