# Generated by Django 4.2.27 on 2025-12-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_returnable_product_return_window_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_emi_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_tax_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
