# Generated by Django 4.2.27 on 2025-12-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_emi_eligible_product_is_tax_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='emi_plan_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of supported EMI Plan UUIDs'),
        ),
    ]
