# Generated by Django 4.2.27 on 2025-12-10 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('is_published', models.BooleanField(default=True)),
                ('target_audience', models.CharField(choices=[('all', 'All Employees'), ('department', 'Specific Department')], default='all', max_length=20)),
                ('target_department', models.CharField(blank=True, help_text='Exact name of the department if targeting specific department', max_length=100, null=True)),
                ('created_by', models.UUIDField(help_text='User UUID of the creator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
