# Generated by Django 4.2 on 2025-12-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesforecast',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='company_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='forecast_type',
            field=models.CharField(default='sales', max_length=50),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='product_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='salesforecast',
            index=models.Index(fields=['company_uuid', 'product_uuid'], name='forecasts_s_company_22be3a_idx'),
        ),
    ]
