# Generated by Django 4.2 on 2025-12-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_alter_salesforecast_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_uuid', models.UUIDField(db_index=True)),
                ('product_name', models.CharField(max_length=255)),
                ('forecast_date', models.DateField(db_index=True)),
                ('predicted_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('algorithm_used', models.CharField(default='simple_moving_average', max_length=50)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_uuid', models.UUIDField(db_index=True)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(db_index=True)),
                ('quantity_sold', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('company_uuid', models.UUIDField(db_index=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SalesForecast',
        ),
        migrations.AddIndex(
            model_name='saleshistory',
            index=models.Index(fields=['company_uuid', 'date'], name='forecasts_s_company_0b5a01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saleshistory',
            unique_together={('product_uuid', 'date', 'company_uuid')},
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together={('product_uuid', 'forecast_date', 'company_uuid')},
        ),
    ]
