/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounting/ledger/accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accounting_ledger_accounts_list"];
        put?: never;
        post: operations["accounting_ledger_accounts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounting/ledger/accounts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accounting_ledger_accounts_retrieve"];
        put: operations["accounting_ledger_accounts_update"];
        post?: never;
        delete: operations["accounting_ledger_accounts_destroy"];
        options?: never;
        head?: never;
        patch: operations["accounting_ledger_accounts_partial_update"];
        trace?: never;
    };
    "/api/accounting/ledger/groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accounting_ledger_groups_list"];
        put?: never;
        post: operations["accounting_ledger_groups_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounting/ledger/groups/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accounting_ledger_groups_retrieve"];
        put: operations["accounting_ledger_groups_update"];
        post?: never;
        delete: operations["accounting_ledger_groups_destroy"];
        options?: never;
        head?: never;
        patch: operations["accounting_ledger_groups_partial_update"];
        trace?: never;
    };
    "/api/accounting/ledger/journals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accounting_ledger_journals_list"];
        put?: never;
        post: operations["accounting_ledger_journals_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounting/ledger/journals/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accounting_ledger_journals_retrieve"];
        put: operations["accounting_ledger_journals_update"];
        post?: never;
        delete: operations["accounting_ledger_journals_destroy"];
        options?: never;
        head?: never;
        patch: operations["accounting_ledger_journals_partial_update"];
        trace?: never;
    };
    "/api/accounting/tax/rates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accounting_tax_rates_list"];
        put?: never;
        post: operations["accounting_tax_rates_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounting/tax/rates/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["accounting_tax_rates_retrieve"];
        put: operations["accounting_tax_rates_update"];
        post?: never;
        delete: operations["accounting_tax_rates_destroy"];
        options?: never;
        head?: never;
        patch: operations["accounting_tax_rates_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountGroup: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            company_uuid: string;
            name: string;
            code?: string;
            group_type: components["schemas"]["GroupTypeEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            parent?: string | null;
        };
        ChartOfAccount: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            company_uuid: string;
            name: string;
            code: string;
            /** Format: decimal */
            opening_balance?: string;
            /** Format: decimal */
            current_balance?: string;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            group: string;
        };
        /**
         * @description * `asset` - Asset
         *     * `liability` - Liability
         *     * `equity` - Equity
         *     * `income` - Income
         *     * `expense` - Expense
         * @enum {string}
         */
        GroupTypeEnum: "asset" | "liability" | "equity" | "income" | "expense";
        JournalEntry: {
            /** Format: uuid */
            readonly id: string;
            items: components["schemas"]["JournalItem"][];
            /** Format: uuid */
            company_uuid: string;
            /** Format: date */
            date: string;
            reference?: string;
            description?: string;
            /** Format: decimal */
            total_debit?: string;
            /** Format: decimal */
            total_credit?: string;
            /** Format: uuid */
            posted_by?: string | null;
            is_posted?: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        JournalItem: {
            /** Format: uuid */
            account: string;
            /** Format: decimal */
            debit?: string;
            /** Format: decimal */
            credit?: string;
            description?: string;
        };
        PaginatedAccountGroupList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["AccountGroup"][];
        };
        PaginatedChartOfAccountList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ChartOfAccount"][];
        };
        PaginatedJournalEntryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["JournalEntry"][];
        };
        PaginatedTaxList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Tax"][];
        };
        PatchedAccountGroup: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            company_uuid?: string;
            name?: string;
            code?: string;
            group_type?: components["schemas"]["GroupTypeEnum"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: uuid */
            parent?: string | null;
        };
        PatchedChartOfAccount: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            company_uuid?: string;
            name?: string;
            code?: string;
            /** Format: decimal */
            opening_balance?: string;
            /** Format: decimal */
            current_balance?: string;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: uuid */
            group?: string;
        };
        PatchedJournalEntry: {
            /** Format: uuid */
            readonly id?: string;
            items?: components["schemas"]["JournalItem"][];
            /** Format: uuid */
            company_uuid?: string;
            /** Format: date */
            date?: string;
            reference?: string;
            description?: string;
            /** Format: decimal */
            total_debit?: string;
            /** Format: decimal */
            total_credit?: string;
            /** Format: uuid */
            posted_by?: string | null;
            is_posted?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
        };
        PatchedTax: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            company_uuid?: string;
            name?: string;
            /** Format: decimal */
            rate?: string;
            /**
             * Format: uuid
             * @description UUID of Liability Account (Output Tax)
             */
            account_payable?: string | null;
            /**
             * Format: uuid
             * @description UUID of Asset Account (Input Tax)
             */
            account_receivable?: string | null;
            description?: string;
            is_active?: boolean;
        };
        Tax: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            company_uuid: string;
            name: string;
            /** Format: decimal */
            rate: string;
            /**
             * Format: uuid
             * @description UUID of Liability Account (Output Tax)
             */
            account_payable?: string | null;
            /**
             * Format: uuid
             * @description UUID of Asset Account (Input Tax)
             */
            account_receivable?: string | null;
            description?: string;
            is_active?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accounting_ledger_accounts_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedChartOfAccountList"];
                };
            };
        };
    };
    accounting_ledger_accounts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartOfAccount"];
                "application/x-www-form-urlencoded": components["schemas"]["ChartOfAccount"];
                "multipart/form-data": components["schemas"]["ChartOfAccount"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartOfAccount"];
                };
            };
        };
    };
    accounting_ledger_accounts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this chart of account. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartOfAccount"];
                };
            };
        };
    };
    accounting_ledger_accounts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this chart of account. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartOfAccount"];
                "application/x-www-form-urlencoded": components["schemas"]["ChartOfAccount"];
                "multipart/form-data": components["schemas"]["ChartOfAccount"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartOfAccount"];
                };
            };
        };
    };
    accounting_ledger_accounts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this chart of account. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounting_ledger_accounts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this chart of account. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedChartOfAccount"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedChartOfAccount"];
                "multipart/form-data": components["schemas"]["PatchedChartOfAccount"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartOfAccount"];
                };
            };
        };
    };
    accounting_ledger_groups_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAccountGroupList"];
                };
            };
        };
    };
    accounting_ledger_groups_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountGroup"];
                "application/x-www-form-urlencoded": components["schemas"]["AccountGroup"];
                "multipart/form-data": components["schemas"]["AccountGroup"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountGroup"];
                };
            };
        };
    };
    accounting_ledger_groups_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this account group. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountGroup"];
                };
            };
        };
    };
    accounting_ledger_groups_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this account group. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountGroup"];
                "application/x-www-form-urlencoded": components["schemas"]["AccountGroup"];
                "multipart/form-data": components["schemas"]["AccountGroup"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountGroup"];
                };
            };
        };
    };
    accounting_ledger_groups_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this account group. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounting_ledger_groups_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this account group. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAccountGroup"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAccountGroup"];
                "multipart/form-data": components["schemas"]["PatchedAccountGroup"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountGroup"];
                };
            };
        };
    };
    accounting_ledger_journals_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJournalEntryList"];
                };
            };
        };
    };
    accounting_ledger_journals_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalEntry"];
                "application/x-www-form-urlencoded": components["schemas"]["JournalEntry"];
                "multipart/form-data": components["schemas"]["JournalEntry"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
        };
    };
    accounting_ledger_journals_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this journal entry. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
        };
    };
    accounting_ledger_journals_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this journal entry. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JournalEntry"];
                "application/x-www-form-urlencoded": components["schemas"]["JournalEntry"];
                "multipart/form-data": components["schemas"]["JournalEntry"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
        };
    };
    accounting_ledger_journals_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this journal entry. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounting_ledger_journals_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this journal entry. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedJournalEntry"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedJournalEntry"];
                "multipart/form-data": components["schemas"]["PatchedJournalEntry"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JournalEntry"];
                };
            };
        };
    };
    accounting_tax_rates_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTaxList"];
                };
            };
        };
    };
    accounting_tax_rates_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Tax"];
                "application/x-www-form-urlencoded": components["schemas"]["Tax"];
                "multipart/form-data": components["schemas"]["Tax"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tax"];
                };
            };
        };
    };
    accounting_tax_rates_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this tax. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tax"];
                };
            };
        };
    };
    accounting_tax_rates_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this tax. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Tax"];
                "application/x-www-form-urlencoded": components["schemas"]["Tax"];
                "multipart/form-data": components["schemas"]["Tax"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tax"];
                };
            };
        };
    };
    accounting_tax_rates_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this tax. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounting_tax_rates_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this tax. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTax"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTax"];
                "multipart/form-data": components["schemas"]["PatchedTax"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tax"];
                };
            };
        };
    };
}
