/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/company/account-groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["account_groups_list"];
        put?: never;
        post: operations["account_groups_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/account-groups/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["account_groups_retrieve"];
        put: operations["account_groups_update"];
        post?: never;
        delete: operations["account_groups_destroy"];
        options?: never;
        head?: never;
        patch: operations["account_groups_partial_update"];
        trace?: never;
    };
    "/api/company/chart-of-accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chart_of_accounts_list"];
        put?: never;
        post: operations["chart_of_accounts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/chart-of-accounts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chart_of_accounts_retrieve"];
        put: operations["chart_of_accounts_update"];
        post?: never;
        delete: operations["chart_of_accounts_destroy"];
        options?: never;
        head?: never;
        patch: operations["chart_of_accounts_partial_update"];
        trace?: never;
    };
    "/api/company/currencies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currencies_list"];
        put?: never;
        post: operations["currencies_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/currencies/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currencies_retrieve"];
        put: operations["currencies_update"];
        post?: never;
        delete: operations["currencies_destroy"];
        options?: never;
        head?: never;
        patch: operations["currencies_partial_update"];
        trace?: never;
    };
    "/api/company/departments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["departments_list"];
        put?: never;
        post: operations["departments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/departments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["departments_retrieve"];
        put: operations["departments_update"];
        post?: never;
        delete: operations["departments_destroy"];
        options?: never;
        head?: never;
        patch: operations["departments_partial_update"];
        trace?: never;
    };
    "/api/company/designations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["designations_list"];
        put?: never;
        post: operations["designations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/designations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["designations_retrieve"];
        put: operations["designations_update"];
        post?: never;
        delete: operations["designations_destroy"];
        options?: never;
        head?: never;
        patch: operations["designations_partial_update"];
        trace?: never;
    };
    "/api/company/employees/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["employees_list"];
        put?: never;
        post: operations["employees_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/employees/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["employees_retrieve"];
        put: operations["employees_update"];
        post?: never;
        delete: operations["employees_destroy"];
        options?: never;
        head?: never;
        patch: operations["employees_partial_update"];
        trace?: never;
    };
    "/api/company/info/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/company/info/
         *     Returns company meta + menus + settings
         */
        get: operations["info_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/invoice-settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["invoice_settings_list"];
        put?: never;
        post: operations["invoice_settings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/invoice-settings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["invoice_settings_retrieve"];
        put: operations["invoice_settings_update"];
        post?: never;
        delete: operations["invoice_settings_destroy"];
        options?: never;
        head?: never;
        patch: operations["invoice_settings_partial_update"];
        trace?: never;
    };
    "/api/company/navigation/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["navigation_list"];
        put?: never;
        post: operations["navigation_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/navigation/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["navigation_retrieve"];
        put: operations["navigation_update"];
        post?: never;
        delete: operations["navigation_destroy"];
        options?: never;
        head?: never;
        patch: operations["navigation_partial_update"];
        trace?: never;
    };
    "/api/company/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["settings_list"];
        put?: never;
        post: operations["settings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/settings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["settings_retrieve"];
        put: operations["settings_update"];
        post?: never;
        delete: operations["settings_destroy"];
        options?: never;
        head?: never;
        patch: operations["settings_partial_update"];
        trace?: never;
    };
    "/api/company/wings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["wings_list"];
        put?: never;
        post: operations["wings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/wings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["wings_retrieve"];
        put: operations["wings_update"];
        post?: never;
        delete: operations["wings_destroy"];
        options?: never;
        head?: never;
        patch: operations["wings_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountGroup: {
            /** Format: uuid */
            readonly id: string;
            readonly subgroups: string;
            name: string;
            code?: string | null;
            /**
             * @description * `asset` - Asset
             *     * `liability` - Liability
             *     * `equity` - Equity
             *     * `income` - Income
             *     * `expense` - Expense
             * @enum {string}
             */
            group_type: "asset" | "liability" | "equity" | "income" | "expense";
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            readonly company: string;
            /** Format: uuid */
            parent?: string | null;
        };
        AccountGroupRequest: {
            name: string;
            code?: string | null;
            /**
             * @description * `asset` - Asset
             *     * `liability` - Liability
             *     * `equity` - Equity
             *     * `income` - Income
             *     * `expense` - Expense
             * @enum {string}
             */
            group_type: "asset" | "liability" | "equity" | "income" | "expense";
            /** Format: uuid */
            parent?: string | null;
        };
        ChartOfAccount: {
            /** Format: uuid */
            readonly id: string;
            readonly group_name: string;
            name: string;
            code?: string | null;
            /** Format: decimal */
            opening_balance?: string;
            /** Format: decimal */
            readonly current_balance: string;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            readonly company: string;
            /** Format: uuid */
            group: string;
        };
        ChartOfAccountRequest: {
            name: string;
            code?: string | null;
            /** Format: decimal */
            opening_balance?: string;
            is_active?: boolean;
            /** Format: uuid */
            group: string;
        };
        CompanySetting: {
            readonly id: number;
            primary_color?: string | null;
            secondary_color?: string | null;
            accent_color?: string | null;
            background_color?: string | null;
            text_color?: string | null;
            logo?: string | null;
            favicon?: string | null;
            readonly feature_flags: unknown;
            ui_schema?: unknown;
        };
        CompanySettingRequest: {
            primary_color?: string | null;
            secondary_color?: string | null;
            accent_color?: string | null;
            background_color?: string | null;
            text_color?: string | null;
            logo?: string | null;
            favicon?: string | null;
            ui_schema?: unknown;
        };
        Currency: {
            readonly id: number;
            code: string;
            name: string;
            symbol?: string;
            /** Format: decimal */
            exchange_rate?: string;
            is_base?: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        CurrencyRequest: {
            code: string;
            name: string;
            symbol?: string;
            /** Format: decimal */
            exchange_rate?: string;
            is_base?: boolean;
        };
        Department: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            description?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            readonly company: string;
        };
        DepartmentRequest: {
            name: string;
            description?: string | null;
        };
        Designation: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            /** @description 1 is highest */
            rank?: number;
            description?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            readonly company: string;
        };
        DesignationRequest: {
            name: string;
            /** @description 1 is highest */
            rank?: number;
            description?: string | null;
        };
        Employee: {
            /** Format: uuid */
            readonly id: string;
            readonly department_name: string;
            readonly designation_name: string;
            /**
             * Format: uuid
             * @description Link to Auth Service User UUID
             */
            user_uuid?: string | null;
            employee_code?: string | null;
            first_name: string;
            last_name?: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            /** Format: date */
            date_of_birth?: string | null;
            /** Format: date */
            joining_date?: string | null;
            /** Format: decimal */
            salary?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly date_joined: string;
            photo?: string | null;
            /** Format: uuid */
            readonly company: string;
            /** Format: uuid */
            department?: string | null;
            /** Format: uuid */
            designation?: string | null;
            /** Format: uuid */
            manager?: string | null;
        };
        EmployeeRequest: {
            /**
             * Format: uuid
             * @description Link to Auth Service User UUID
             */
            user_uuid?: string | null;
            employee_code?: string | null;
            first_name: string;
            last_name?: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            /** Format: date */
            date_of_birth?: string | null;
            /** Format: date */
            joining_date?: string | null;
            /** Format: decimal */
            salary?: string | null;
            is_active?: boolean;
            photo?: string | null;
            /** Format: uuid */
            department?: string | null;
            /** Format: uuid */
            designation?: string | null;
            /** Format: uuid */
            manager?: string | null;
        };
        InvoiceSettings: {
            readonly id: number;
            invoice_prefix?: string;
            readonly next_invoice_number: number;
            allow_negative_stock?: boolean;
            tax_inclusive?: boolean;
            /**
             * @description * `standard` - Standard
             *     * `compact` - Compact
             *     * `detailed` - Detailed
             * @enum {string}
             */
            template?: "standard" | "compact" | "detailed";
            footer_note?: string;
            readonly sequence_name: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: uuid */
            readonly company: string;
            default_currency?: number | null;
        };
        InvoiceSettingsRequest: {
            invoice_prefix?: string;
            allow_negative_stock?: boolean;
            tax_inclusive?: boolean;
            /**
             * @description * `standard` - Standard
             *     * `compact` - Compact
             *     * `detailed` - Detailed
             * @enum {string}
             */
            template?: "standard" | "compact" | "detailed";
            footer_note?: string;
            default_currency?: number | null;
        };
        NavigationItem: {
            /** Format: uuid */
            readonly id: string;
            title: string;
            path?: string | null;
            order?: number;
            permission_code?: string | null;
            metadata?: unknown;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            readonly company: string;
            /** Format: uuid */
            parent?: string | null;
        };
        NavigationItemRequest: {
            title: string;
            path?: string | null;
            order?: number;
            permission_code?: string | null;
            metadata?: unknown;
            /** Format: uuid */
            parent?: string | null;
        };
        PaginatedAccountGroupList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["AccountGroup"][];
        };
        PaginatedChartOfAccountList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["ChartOfAccount"][];
        };
        PaginatedCompanySettingList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["CompanySetting"][];
        };
        PaginatedCurrencyList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Currency"][];
        };
        PaginatedDepartmentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Department"][];
        };
        PaginatedDesignationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Designation"][];
        };
        PaginatedEmployeeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Employee"][];
        };
        PaginatedInvoiceSettingsList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["InvoiceSettings"][];
        };
        PaginatedNavigationItemList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["NavigationItem"][];
        };
        PaginatedWingList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=400&limit=100
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?offset=200&limit=100
             */
            previous?: string | null;
            results: components["schemas"]["Wing"][];
        };
        PatchedAccountGroupRequest: {
            name?: string;
            code?: string | null;
            /**
             * @description * `asset` - Asset
             *     * `liability` - Liability
             *     * `equity` - Equity
             *     * `income` - Income
             *     * `expense` - Expense
             * @enum {string}
             */
            group_type?: "asset" | "liability" | "equity" | "income" | "expense";
            /** Format: uuid */
            parent?: string | null;
        };
        PatchedChartOfAccountRequest: {
            name?: string;
            code?: string | null;
            /** Format: decimal */
            opening_balance?: string;
            is_active?: boolean;
            /** Format: uuid */
            group?: string;
        };
        PatchedCompanySettingRequest: {
            primary_color?: string | null;
            secondary_color?: string | null;
            accent_color?: string | null;
            background_color?: string | null;
            text_color?: string | null;
            logo?: string | null;
            favicon?: string | null;
            ui_schema?: unknown;
        };
        PatchedCurrencyRequest: {
            code?: string;
            name?: string;
            symbol?: string;
            /** Format: decimal */
            exchange_rate?: string;
            is_base?: boolean;
        };
        PatchedDepartmentRequest: {
            name?: string;
            description?: string | null;
        };
        PatchedDesignationRequest: {
            name?: string;
            /** @description 1 is highest */
            rank?: number;
            description?: string | null;
        };
        PatchedEmployeeRequest: {
            /**
             * Format: uuid
             * @description Link to Auth Service User UUID
             */
            user_uuid?: string | null;
            employee_code?: string | null;
            first_name?: string;
            last_name?: string;
            /** Format: email */
            email?: string | null;
            phone?: string | null;
            /** Format: date */
            date_of_birth?: string | null;
            /** Format: date */
            joining_date?: string | null;
            /** Format: decimal */
            salary?: string | null;
            is_active?: boolean;
            photo?: string | null;
            /** Format: uuid */
            department?: string | null;
            /** Format: uuid */
            designation?: string | null;
            /** Format: uuid */
            manager?: string | null;
        };
        PatchedInvoiceSettingsRequest: {
            invoice_prefix?: string;
            allow_negative_stock?: boolean;
            tax_inclusive?: boolean;
            /**
             * @description * `standard` - Standard
             *     * `compact` - Compact
             *     * `detailed` - Detailed
             * @enum {string}
             */
            template?: "standard" | "compact" | "detailed";
            footer_note?: string;
            default_currency?: number | null;
        };
        PatchedNavigationItemRequest: {
            title?: string;
            path?: string | null;
            order?: number;
            permission_code?: string | null;
            metadata?: unknown;
            /** Format: uuid */
            parent?: string | null;
        };
        PatchedWingRequest: {
            name?: string;
            code?: string;
            pos_printer_name?: string | null;
            pos_config?: unknown;
            metadata?: unknown;
        };
        Wing: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            code: string;
            pos_printer_name?: string | null;
            pos_config?: unknown;
            metadata?: unknown;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: uuid */
            readonly company: string;
        };
        WingRequest: {
            name: string;
            code: string;
            pos_printer_name?: string | null;
            pos_config?: unknown;
            metadata?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    account_groups_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAccountGroupList"];
                };
            };
        };
    };
    account_groups_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountGroupRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AccountGroupRequest"];
                "multipart/form-data": components["schemas"]["AccountGroupRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountGroup"];
                };
            };
        };
    };
    account_groups_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this account group. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountGroup"];
                };
            };
        };
    };
    account_groups_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this account group. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountGroupRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AccountGroupRequest"];
                "multipart/form-data": components["schemas"]["AccountGroupRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountGroup"];
                };
            };
        };
    };
    account_groups_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this account group. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    account_groups_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this account group. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAccountGroupRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAccountGroupRequest"];
                "multipart/form-data": components["schemas"]["PatchedAccountGroupRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountGroup"];
                };
            };
        };
    };
    chart_of_accounts_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedChartOfAccountList"];
                };
            };
        };
    };
    chart_of_accounts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartOfAccountRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChartOfAccountRequest"];
                "multipart/form-data": components["schemas"]["ChartOfAccountRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartOfAccount"];
                };
            };
        };
    };
    chart_of_accounts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this chart of account. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartOfAccount"];
                };
            };
        };
    };
    chart_of_accounts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this chart of account. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChartOfAccountRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChartOfAccountRequest"];
                "multipart/form-data": components["schemas"]["ChartOfAccountRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartOfAccount"];
                };
            };
        };
    };
    chart_of_accounts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this chart of account. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chart_of_accounts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this chart of account. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedChartOfAccountRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedChartOfAccountRequest"];
                "multipart/form-data": components["schemas"]["PatchedChartOfAccountRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartOfAccount"];
                };
            };
        };
    };
    currencies_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCurrencyList"];
                };
            };
        };
    };
    currencies_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurrencyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CurrencyRequest"];
                "multipart/form-data": components["schemas"]["CurrencyRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Currency"];
                };
            };
        };
    };
    currencies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this currency. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Currency"];
                };
            };
        };
    };
    currencies_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this currency. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurrencyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CurrencyRequest"];
                "multipart/form-data": components["schemas"]["CurrencyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Currency"];
                };
            };
        };
    };
    currencies_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this currency. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    currencies_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this currency. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCurrencyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCurrencyRequest"];
                "multipart/form-data": components["schemas"]["PatchedCurrencyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Currency"];
                };
            };
        };
    };
    departments_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDepartmentList"];
                };
            };
        };
    };
    departments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DepartmentRequest"];
                "multipart/form-data": components["schemas"]["DepartmentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    departments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    departments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DepartmentRequest"];
                "multipart/form-data": components["schemas"]["DepartmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    departments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    departments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this department. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDepartmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDepartmentRequest"];
                "multipart/form-data": components["schemas"]["PatchedDepartmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Department"];
                };
            };
        };
    };
    designations_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDesignationList"];
                };
            };
        };
    };
    designations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesignationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DesignationRequest"];
                "multipart/form-data": components["schemas"]["DesignationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Designation"];
                };
            };
        };
    };
    designations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this designation. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Designation"];
                };
            };
        };
    };
    designations_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this designation. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesignationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DesignationRequest"];
                "multipart/form-data": components["schemas"]["DesignationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Designation"];
                };
            };
        };
    };
    designations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this designation. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    designations_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this designation. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDesignationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDesignationRequest"];
                "multipart/form-data": components["schemas"]["PatchedDesignationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Designation"];
                };
            };
        };
    };
    employees_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedEmployeeList"];
                };
            };
        };
    };
    employees_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmployeeRequest"];
                "multipart/form-data": components["schemas"]["EmployeeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    employees_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    employees_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EmployeeRequest"];
                "multipart/form-data": components["schemas"]["EmployeeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    employees_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    employees_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this employee. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEmployeeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedEmployeeRequest"];
                "multipart/form-data": components["schemas"]["PatchedEmployeeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
        };
    };
    info_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invoice_settings_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedInvoiceSettingsList"];
                };
            };
        };
    };
    invoice_settings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["InvoiceSettingsRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["InvoiceSettingsRequest"];
                "multipart/form-data": components["schemas"]["InvoiceSettingsRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceSettings"];
                };
            };
        };
    };
    invoice_settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this invoice settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceSettings"];
                };
            };
        };
    };
    invoice_settings_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this invoice settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["InvoiceSettingsRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["InvoiceSettingsRequest"];
                "multipart/form-data": components["schemas"]["InvoiceSettingsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceSettings"];
                };
            };
        };
    };
    invoice_settings_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this invoice settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invoice_settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this invoice settings. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedInvoiceSettingsRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedInvoiceSettingsRequest"];
                "multipart/form-data": components["schemas"]["PatchedInvoiceSettingsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceSettings"];
                };
            };
        };
    };
    navigation_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNavigationItemList"];
                };
            };
        };
    };
    navigation_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NavigationItemRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NavigationItemRequest"];
                "multipart/form-data": components["schemas"]["NavigationItemRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationItem"];
                };
            };
        };
    };
    navigation_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this navigation item. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationItem"];
                };
            };
        };
    };
    navigation_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this navigation item. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NavigationItemRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NavigationItemRequest"];
                "multipart/form-data": components["schemas"]["NavigationItemRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationItem"];
                };
            };
        };
    };
    navigation_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this navigation item. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    navigation_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this navigation item. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNavigationItemRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNavigationItemRequest"];
                "multipart/form-data": components["schemas"]["PatchedNavigationItemRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavigationItem"];
                };
            };
        };
    };
    settings_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCompanySettingList"];
                };
            };
        };
    };
    settings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CompanySettingRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CompanySettingRequest"];
                "multipart/form-data": components["schemas"]["CompanySettingRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySetting"];
                };
            };
        };
    };
    settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this company setting. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySetting"];
                };
            };
        };
    };
    settings_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this company setting. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CompanySettingRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CompanySettingRequest"];
                "multipart/form-data": components["schemas"]["CompanySettingRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySetting"];
                };
            };
        };
    };
    settings_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this company setting. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this company setting. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCompanySettingRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCompanySettingRequest"];
                "multipart/form-data": components["schemas"]["PatchedCompanySettingRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanySetting"];
                };
            };
        };
    };
    wings_list: {
        parameters: {
            query?: {
                /** @description Number of results to return per page. */
                limit?: number;
                /** @description The initial index from which to return the results. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWingList"];
                };
            };
        };
    };
    wings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WingRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WingRequest"];
                "multipart/form-data": components["schemas"]["WingRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wing"];
                };
            };
        };
    };
    wings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this wing. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wing"];
                };
            };
        };
    };
    wings_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this wing. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WingRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["WingRequest"];
                "multipart/form-data": components["schemas"]["WingRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wing"];
                };
            };
        };
    };
    wings_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this wing. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    wings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this wing. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedWingRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedWingRequest"];
                "multipart/form-data": components["schemas"]["PatchedWingRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wing"];
                };
            };
        };
    };
}
