/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/intelligence/automation/logs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["automation_logs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intelligence/automation/logs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["automation_logs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intelligence/automation/rules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["automation_rules_list"];
        put?: never;
        post: operations["automation_rules_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intelligence/automation/rules/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["automation_rules_retrieve"];
        put: operations["automation_rules_update"];
        post?: never;
        delete: operations["automation_rules_destroy"];
        options?: never;
        head?: never;
        patch: operations["automation_rules_partial_update"];
        trace?: never;
    };
    "/api/intelligence/automation/trigger/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["automation_trigger_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intelligence/customers/segments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["customers_segments_list"];
        put?: never;
        post: operations["customers_segments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intelligence/customers/segments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["customers_segments_retrieve"];
        put: operations["customers_segments_update"];
        post?: never;
        delete: operations["customers_segments_destroy"];
        options?: never;
        head?: never;
        patch: operations["customers_segments_partial_update"];
        trace?: never;
    };
    "/api/intelligence/forecast/sales/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["forecast_sales_list"];
        put?: never;
        post: operations["forecast_sales_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intelligence/forecast/sales/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["forecast_sales_retrieve"];
        put: operations["forecast_sales_update"];
        post?: never;
        delete: operations["forecast_sales_destroy"];
        options?: never;
        head?: never;
        patch: operations["forecast_sales_partial_update"];
        trace?: never;
    };
    "/api/intelligence/hr/attrition-risk/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["hr_attrition_risk_retrieve"];
        put?: never;
        post: operations["hr_attrition_risk_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intelligence/inventory/opt/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["inventory_opt_list"];
        put?: never;
        post: operations["inventory_opt_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intelligence/inventory/opt/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["inventory_opt_retrieve"];
        put: operations["inventory_opt_update"];
        post?: never;
        delete: operations["inventory_opt_destroy"];
        options?: never;
        head?: never;
        patch: operations["inventory_opt_partial_update"];
        trace?: never;
    };
    "/api/intelligence/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActionLog: {
            /** Format: uuid */
            readonly id: string;
            status?: string;
            details?: string;
            /** Format: date-time */
            readonly executed_at: string;
            /** Format: uuid */
            rule: string;
        };
        /**
         * @description * `email` - Send Email
         *     * `sms` - Send SMS
         *     * `log` - Log Alert
         *     * `webhook` - Call Webhook
         *     * `create_task` - Create Task
         * @enum {string}
         */
        ActionTypeEnum: "email" | "sms" | "log" | "webhook" | "create_task";
        AutomationRule: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            is_active?: boolean;
            trigger_type: components["schemas"]["TriggerTypeEnum"];
            condition_field?: string | null;
            condition_operator?: string;
            condition_value?: string | null;
            action_type: components["schemas"]["ActionTypeEnum"];
            action_config?: unknown;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        CustomerSegmentation: {
            readonly id: number;
            /** Format: email */
            customer_email: string;
            /** @description Days since last purchase */
            recency: number;
            /** @description Total number of orders */
            frequency: number;
            /**
             * Format: decimal
             * @description Total spend
             */
            monetary: string;
            r_score: number;
            f_score: number;
            m_score: number;
            segment_label: string;
            /** Format: date-time */
            readonly last_updated: string;
        };
        InventoryOptimization: {
            readonly id: number;
            /** Format: uuid */
            product_uuid: string;
            /** Format: uuid */
            branch_id?: string | null;
            current_stock: number;
            /** Format: double */
            avg_daily_consumption: number;
            suggested_reorder_point: number;
            suggested_reorder_qty: number;
            /** Format: date-time */
            readonly last_updated: string;
        };
        PatchedAutomationRule: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            is_active?: boolean;
            trigger_type?: components["schemas"]["TriggerTypeEnum"];
            condition_field?: string | null;
            condition_operator?: string;
            condition_value?: string | null;
            action_type?: components["schemas"]["ActionTypeEnum"];
            action_config?: unknown;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedCustomerSegmentation: {
            readonly id?: number;
            /** Format: email */
            customer_email?: string;
            /** @description Days since last purchase */
            recency?: number;
            /** @description Total number of orders */
            frequency?: number;
            /**
             * Format: decimal
             * @description Total spend
             */
            monetary?: string;
            r_score?: number;
            f_score?: number;
            m_score?: number;
            segment_label?: string;
            /** Format: date-time */
            readonly last_updated?: string;
        };
        PatchedInventoryOptimization: {
            readonly id?: number;
            /** Format: uuid */
            product_uuid?: string;
            /** Format: uuid */
            branch_id?: string | null;
            current_stock?: number;
            /** Format: double */
            avg_daily_consumption?: number;
            suggested_reorder_point?: number;
            suggested_reorder_qty?: number;
            /** Format: date-time */
            readonly last_updated?: string;
        };
        PatchedSalesForecast: {
            readonly id?: number;
            /** Format: date */
            date?: string;
            /** Format: double */
            predicted_sales?: number;
            /** Format: double */
            confidence_lower?: number | null;
            /** Format: double */
            confidence_upper?: number | null;
            /** Format: date-time */
            readonly created_at?: string;
        };
        SalesForecast: {
            readonly id: number;
            /** Format: date */
            date: string;
            /** Format: double */
            predicted_sales: number;
            /** Format: double */
            confidence_lower?: number | null;
            /** Format: double */
            confidence_upper?: number | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `stock_level` - Stock Level Change
         *     * `new_order` - New Order
         *     * `payment_failed` - Payment Failed
         *     * `shipment_status` - Shipment Status Change
         *     * `scheduled` - Scheduled Time
         * @enum {string}
         */
        TriggerTypeEnum: "stock_level" | "new_order" | "payment_failed" | "shipment_status" | "scheduled";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    automation_logs_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionLog"][];
                };
            };
        };
    };
    automation_logs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this action log. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionLog"];
                };
            };
        };
    };
    automation_rules_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutomationRule"][];
                };
            };
        };
    };
    automation_rules_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutomationRule"];
                "application/x-www-form-urlencoded": components["schemas"]["AutomationRule"];
                "multipart/form-data": components["schemas"]["AutomationRule"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutomationRule"];
                };
            };
        };
    };
    automation_rules_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this automation rule. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutomationRule"];
                };
            };
        };
    };
    automation_rules_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this automation rule. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutomationRule"];
                "application/x-www-form-urlencoded": components["schemas"]["AutomationRule"];
                "multipart/form-data": components["schemas"]["AutomationRule"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutomationRule"];
                };
            };
        };
    };
    automation_rules_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this automation rule. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    automation_rules_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this automation rule. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAutomationRule"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAutomationRule"];
                "multipart/form-data": components["schemas"]["PatchedAutomationRule"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutomationRule"];
                };
            };
        };
    };
    automation_trigger_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    customers_segments_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSegmentation"][];
                };
            };
        };
    };
    customers_segments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerSegmentation"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomerSegmentation"];
                "multipart/form-data": components["schemas"]["CustomerSegmentation"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSegmentation"];
                };
            };
        };
    };
    customers_segments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this customer segmentation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSegmentation"];
                };
            };
        };
    };
    customers_segments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this customer segmentation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerSegmentation"];
                "application/x-www-form-urlencoded": components["schemas"]["CustomerSegmentation"];
                "multipart/form-data": components["schemas"]["CustomerSegmentation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSegmentation"];
                };
            };
        };
    };
    customers_segments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this customer segmentation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    customers_segments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this customer segmentation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCustomerSegmentation"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCustomerSegmentation"];
                "multipart/form-data": components["schemas"]["PatchedCustomerSegmentation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerSegmentation"];
                };
            };
        };
    };
    forecast_sales_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesForecast"][];
                };
            };
        };
    };
    forecast_sales_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalesForecast"];
                "application/x-www-form-urlencoded": components["schemas"]["SalesForecast"];
                "multipart/form-data": components["schemas"]["SalesForecast"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesForecast"];
                };
            };
        };
    };
    forecast_sales_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this sales forecast. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesForecast"];
                };
            };
        };
    };
    forecast_sales_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this sales forecast. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SalesForecast"];
                "application/x-www-form-urlencoded": components["schemas"]["SalesForecast"];
                "multipart/form-data": components["schemas"]["SalesForecast"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesForecast"];
                };
            };
        };
    };
    forecast_sales_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this sales forecast. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forecast_sales_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this sales forecast. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSalesForecast"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSalesForecast"];
                "multipart/form-data": components["schemas"]["PatchedSalesForecast"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalesForecast"];
                };
            };
        };
    };
    hr_attrition_risk_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hr_attrition_risk_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inventory_opt_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryOptimization"][];
                };
            };
        };
    };
    inventory_opt_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryOptimization"];
                "application/x-www-form-urlencoded": components["schemas"]["InventoryOptimization"];
                "multipart/form-data": components["schemas"]["InventoryOptimization"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryOptimization"];
                };
            };
        };
    };
    inventory_opt_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this inventory optimization. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryOptimization"];
                };
            };
        };
    };
    inventory_opt_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this inventory optimization. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryOptimization"];
                "application/x-www-form-urlencoded": components["schemas"]["InventoryOptimization"];
                "multipart/form-data": components["schemas"]["InventoryOptimization"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryOptimization"];
                };
            };
        };
    };
    inventory_opt_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this inventory optimization. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inventory_opt_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this inventory optimization. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedInventoryOptimization"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedInventoryOptimization"];
                "multipart/form-data": components["schemas"]["PatchedInventoryOptimization"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryOptimization"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
