/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/inventory/bom/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bom_list"];
        put?: never;
        post: operations["bom_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/bom/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["bom_retrieve"];
        put: operations["bom_update"];
        post?: never;
        delete: operations["bom_destroy"];
        options?: never;
        head?: never;
        patch: operations["bom_partial_update"];
        trace?: never;
    };
    "/api/inventory/manufacturing/boms/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manufacturing_boms_list"];
        put?: never;
        post: operations["manufacturing_boms_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/manufacturing/boms/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manufacturing_boms_retrieve"];
        put: operations["manufacturing_boms_update"];
        post?: never;
        delete: operations["manufacturing_boms_destroy"];
        options?: never;
        head?: never;
        patch: operations["manufacturing_boms_partial_update"];
        trace?: never;
    };
    "/api/inventory/manufacturing/boms/{id}/add_item/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["manufacturing_boms_add_item_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/manufacturing/production-orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manufacturing_production_orders_list"];
        put?: never;
        post: operations["manufacturing_production_orders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/manufacturing/production-orders/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manufacturing_production_orders_retrieve"];
        put: operations["manufacturing_production_orders_update"];
        post?: never;
        delete: operations["manufacturing_production_orders_destroy"];
        options?: never;
        head?: never;
        patch: operations["manufacturing_production_orders_partial_update"];
        trace?: never;
    };
    "/api/inventory/manufacturing/production-orders/{id}/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Mark production order as completed and update stock (logic to be implemented later) */
        post: operations["manufacturing_production_orders_complete_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/manufacturing/work-centers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manufacturing_work_centers_list"];
        put?: never;
        post: operations["manufacturing_work_centers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/manufacturing/work-centers/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manufacturing_work_centers_retrieve"];
        put: operations["manufacturing_work_centers_update"];
        post?: never;
        delete: operations["manufacturing_work_centers_destroy"];
        options?: never;
        head?: never;
        patch: operations["manufacturing_work_centers_partial_update"];
        trace?: never;
    };
    "/api/inventory/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/serials/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["serials_list"];
        put?: never;
        post: operations["serials_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/serials/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["serials_retrieve"];
        put: operations["serials_update"];
        post?: never;
        delete: operations["serials_destroy"];
        options?: never;
        head?: never;
        patch: operations["serials_partial_update"];
        trace?: never;
    };
    "/api/inventory/stocks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stocks_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/stocks/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["stocks_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/stocks/adjust/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stocks_adjust_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/transactions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["transactions_list"];
        put?: never;
        post: operations["transactions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/transactions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["transactions_retrieve"];
        put: operations["transactions_update"];
        post?: never;
        delete: operations["transactions_destroy"];
        options?: never;
        head?: never;
        patch: operations["transactions_partial_update"];
        trace?: never;
    };
    "/api/inventory/uom/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["uom_list"];
        put?: never;
        post: operations["uom_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/uom/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["uom_retrieve"];
        put: operations["uom_update"];
        post?: never;
        delete: operations["uom_destroy"];
        options?: never;
        head?: never;
        patch: operations["uom_partial_update"];
        trace?: never;
    };
    "/api/inventory/warehouses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["warehouses_list"];
        put?: never;
        post: operations["warehouses_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/warehouses/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["warehouses_retrieve"];
        put: operations["warehouses_update"];
        post?: never;
        delete: operations["warehouses_destroy"];
        options?: never;
        head?: never;
        patch: operations["warehouses_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Batch: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            batch_number: string;
            /** Format: date */
            manufacturing_date?: string | null;
            /** Format: date */
            expiry_date?: string | null;
            /** Format: decimal */
            quantity?: string;
            /** Format: decimal */
            cost_price?: string;
            /** Format: decimal */
            sale_price?: string | null;
            /** Format: uuid */
            stock: string;
        };
        BillOfMaterial: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            /** Format: uuid */
            parent_product_uuid: string;
            /** Format: uuid */
            child_product_uuid: string;
            /** Format: decimal */
            quantity: string;
            unit?: string | null;
        };
        ManufacturingBOMItem: {
            readonly id: number;
            /** Format: uuid */
            component_uuid: string;
            /**
             * Format: decimal
             * @description Quantity required per BOM output
             */
            quantity: string;
            /** Format: decimal */
            waste_percentage?: string;
            bom: number;
        };
        ManufacturingBillOfMaterial: {
            readonly id: number;
            readonly items: components["schemas"]["ManufacturingBOMItem"][];
            /** Format: uuid */
            product_uuid: string;
            /** @description e.g. Standard Recipe v1 */
            name: string;
            /**
             * Format: decimal
             * @description Output Quantity
             */
            quantity?: string;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PaginatedBillOfMaterialList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["BillOfMaterial"][];
        };
        PaginatedManufacturingBillOfMaterialList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ManufacturingBillOfMaterial"][];
        };
        PaginatedProductionOrderList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProductionOrder"][];
        };
        PaginatedStockList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Stock"][];
        };
        PaginatedStockSerialList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["StockSerial"][];
        };
        PaginatedStockTransactionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["StockTransaction"][];
        };
        PaginatedUOMConversionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["UOMConversion"][];
        };
        PaginatedWarehouseList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Warehouse"][];
        };
        PaginatedWorkCenterList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["WorkCenter"][];
        };
        PatchedBillOfMaterial: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly company_uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            is_deleted?: boolean;
            /** Format: uuid */
            parent_product_uuid?: string;
            /** Format: uuid */
            child_product_uuid?: string;
            /** Format: decimal */
            quantity?: string;
            unit?: string | null;
        };
        PatchedManufacturingBillOfMaterial: {
            readonly id?: number;
            readonly items?: components["schemas"]["ManufacturingBOMItem"][];
            /** Format: uuid */
            product_uuid?: string;
            /** @description e.g. Standard Recipe v1 */
            name?: string;
            /**
             * Format: decimal
             * @description Output Quantity
             */
            quantity?: string;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        PatchedProductionOrder: {
            readonly id?: number;
            readonly work_center_name?: string;
            readonly bom_name?: string;
            /** Format: uuid */
            product_uuid?: string;
            /** Format: decimal */
            quantity_planned?: string;
            /** Format: decimal */
            quantity_produced?: string;
            status?: components["schemas"]["ProductionOrderStatusEnum"];
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            notes?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            work_center?: number | null;
            bom?: number | null;
        };
        PatchedStockSerial: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly company_uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            is_deleted?: boolean;
            serial_number?: string;
            chassis_number?: string | null;
            engine_number?: string | null;
            color?: string | null;
            status?: components["schemas"]["StockSerialStatusEnum"];
            /** Format: uuid */
            stock?: string;
        };
        PatchedStockTransaction: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly company_uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            is_deleted?: boolean;
            type?: components["schemas"]["TypeEnum"];
            /** Format: decimal */
            quantity_change?: string;
            /** Format: decimal */
            balance_after?: string;
            reference_no?: string | null;
            notes?: string | null;
            created_by?: string | null;
            /** Format: uuid */
            stock?: string;
            /** Format: uuid */
            batch?: string | null;
        };
        PatchedUOMConversion: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly company_uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            is_deleted?: boolean;
            /** Format: uuid */
            product_uuid?: string;
            from_unit?: string;
            to_unit?: string;
            /** Format: decimal */
            factor?: string;
        };
        PatchedWarehouse: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly company_uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            readonly is_deleted?: boolean;
            name?: string;
            address?: string | null;
            is_active?: boolean;
            type?: string;
        };
        PatchedWorkCenter: {
            readonly id?: number;
            name?: string;
            code?: string;
            description?: string;
            /**
             * Format: decimal
             * @description Units per day capacity
             */
            capacity_per_day?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        ProductionOrder: {
            readonly id: number;
            readonly work_center_name: string;
            readonly bom_name: string;
            /** Format: uuid */
            product_uuid: string;
            /** Format: decimal */
            quantity_planned: string;
            /** Format: decimal */
            quantity_produced?: string;
            status?: components["schemas"]["ProductionOrderStatusEnum"];
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            end_date?: string | null;
            notes?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            work_center?: number | null;
            bom?: number | null;
        };
        /**
         * @description * `DRAFT` - Draft
         *     * `CONFIRMED` - Confirmed
         *     * `IN_PROGRESS` - In Progress
         *     * `COMPLETED` - Completed
         *     * `CANCELLED` - Cancelled
         * @enum {string}
         */
        ProductionOrderStatusEnum: "DRAFT" | "CONFIRMED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
        Stock: {
            /** Format: uuid */
            readonly id: string;
            readonly batches: components["schemas"]["Batch"][];
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            /** Format: uuid */
            product_uuid: string;
            /** Format: uuid */
            product_variant_uuid?: string | null;
            /** Format: decimal */
            quantity?: string;
            /** Format: decimal */
            reorder_level?: string;
            /** Format: decimal */
            avg_cost?: string;
            /** Format: uuid */
            warehouse: string;
        };
        StockSerial: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            serial_number: string;
            chassis_number?: string | null;
            engine_number?: string | null;
            color?: string | null;
            status?: components["schemas"]["StockSerialStatusEnum"];
            /** Format: uuid */
            stock: string;
        };
        /**
         * @description * `available` - Available
         *     * `sold` - Sold
         *     * `defective` - Defective
         *     * `returned` - Returned
         *     * `transfer` - In Transfer
         * @enum {string}
         */
        StockSerialStatusEnum: "available" | "sold" | "defective" | "returned" | "transfer";
        StockTransaction: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            type: components["schemas"]["TypeEnum"];
            /** Format: decimal */
            quantity_change: string;
            /** Format: decimal */
            balance_after: string;
            reference_no?: string | null;
            notes?: string | null;
            created_by?: string | null;
            /** Format: uuid */
            stock: string;
            /** Format: uuid */
            batch?: string | null;
        };
        /**
         * @description * `in` - In (Purchase)
         *     * `out` - Out (Sale)
         *     * `transfer_in` - Transfer In
         *     * `transfer_out` - Transfer Out
         *     * `adjustment_add` - Adjustment (Add)
         *     * `adjustment_sub` - Adjustment (Sub)
         *     * `return` - Return
         * @enum {string}
         */
        TypeEnum: "in" | "out" | "transfer_in" | "transfer_out" | "adjustment_add" | "adjustment_sub" | "return";
        UOMConversion: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            /** Format: uuid */
            product_uuid: string;
            from_unit: string;
            to_unit: string;
            /** Format: decimal */
            factor: string;
        };
        Warehouse: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly is_deleted: boolean;
            name: string;
            address?: string | null;
            is_active?: boolean;
            type?: string;
        };
        WorkCenter: {
            readonly id: number;
            name: string;
            code: string;
            description?: string;
            /**
             * Format: decimal
             * @description Units per day capacity
             */
            capacity_per_day: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    bom_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBillOfMaterialList"];
                };
            };
        };
    };
    bom_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillOfMaterial"];
                "application/x-www-form-urlencoded": components["schemas"]["BillOfMaterial"];
                "multipart/form-data": components["schemas"]["BillOfMaterial"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillOfMaterial"];
                };
            };
        };
    };
    bom_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this bill of material. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillOfMaterial"];
                };
            };
        };
    };
    bom_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this bill of material. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillOfMaterial"];
                "application/x-www-form-urlencoded": components["schemas"]["BillOfMaterial"];
                "multipart/form-data": components["schemas"]["BillOfMaterial"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillOfMaterial"];
                };
            };
        };
    };
    bom_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this bill of material. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    bom_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this bill of material. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBillOfMaterial"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBillOfMaterial"];
                "multipart/form-data": components["schemas"]["PatchedBillOfMaterial"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillOfMaterial"];
                };
            };
        };
    };
    manufacturing_boms_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                product_uuid?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedManufacturingBillOfMaterialList"];
                };
            };
        };
    };
    manufacturing_boms_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManufacturingBillOfMaterial"];
                "application/x-www-form-urlencoded": components["schemas"]["ManufacturingBillOfMaterial"];
                "multipart/form-data": components["schemas"]["ManufacturingBillOfMaterial"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManufacturingBillOfMaterial"];
                };
            };
        };
    };
    manufacturing_boms_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this bill of material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManufacturingBillOfMaterial"];
                };
            };
        };
    };
    manufacturing_boms_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this bill of material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManufacturingBillOfMaterial"];
                "application/x-www-form-urlencoded": components["schemas"]["ManufacturingBillOfMaterial"];
                "multipart/form-data": components["schemas"]["ManufacturingBillOfMaterial"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManufacturingBillOfMaterial"];
                };
            };
        };
    };
    manufacturing_boms_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this bill of material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    manufacturing_boms_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this bill of material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedManufacturingBillOfMaterial"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedManufacturingBillOfMaterial"];
                "multipart/form-data": components["schemas"]["PatchedManufacturingBillOfMaterial"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManufacturingBillOfMaterial"];
                };
            };
        };
    };
    manufacturing_boms_add_item_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this bill of material. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManufacturingBillOfMaterial"];
                "application/x-www-form-urlencoded": components["schemas"]["ManufacturingBillOfMaterial"];
                "multipart/form-data": components["schemas"]["ManufacturingBillOfMaterial"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManufacturingBillOfMaterial"];
                };
            };
        };
    };
    manufacturing_production_orders_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                product_uuid?: string;
                /**
                 * @description * `DRAFT` - Draft
                 *     * `CONFIRMED` - Confirmed
                 *     * `IN_PROGRESS` - In Progress
                 *     * `COMPLETED` - Completed
                 *     * `CANCELLED` - Cancelled
                 */
                status?: "CANCELLED" | "COMPLETED" | "CONFIRMED" | "DRAFT" | "IN_PROGRESS";
                work_center?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductionOrderList"];
                };
            };
        };
    };
    manufacturing_production_orders_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductionOrder"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductionOrder"];
                "multipart/form-data": components["schemas"]["ProductionOrder"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionOrder"];
                };
            };
        };
    };
    manufacturing_production_orders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this production order. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionOrder"];
                };
            };
        };
    };
    manufacturing_production_orders_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this production order. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductionOrder"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductionOrder"];
                "multipart/form-data": components["schemas"]["ProductionOrder"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionOrder"];
                };
            };
        };
    };
    manufacturing_production_orders_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this production order. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    manufacturing_production_orders_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this production order. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProductionOrder"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProductionOrder"];
                "multipart/form-data": components["schemas"]["PatchedProductionOrder"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionOrder"];
                };
            };
        };
    };
    manufacturing_production_orders_complete_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this production order. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductionOrder"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductionOrder"];
                "multipart/form-data": components["schemas"]["ProductionOrder"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductionOrder"];
                };
            };
        };
    };
    manufacturing_work_centers_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWorkCenterList"];
                };
            };
        };
    };
    manufacturing_work_centers_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkCenter"];
                "application/x-www-form-urlencoded": components["schemas"]["WorkCenter"];
                "multipart/form-data": components["schemas"]["WorkCenter"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkCenter"];
                };
            };
        };
    };
    manufacturing_work_centers_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this work center. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkCenter"];
                };
            };
        };
    };
    manufacturing_work_centers_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this work center. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkCenter"];
                "application/x-www-form-urlencoded": components["schemas"]["WorkCenter"];
                "multipart/form-data": components["schemas"]["WorkCenter"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkCenter"];
                };
            };
        };
    };
    manufacturing_work_centers_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this work center. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    manufacturing_work_centers_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this work center. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedWorkCenter"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedWorkCenter"];
                "multipart/form-data": components["schemas"]["PatchedWorkCenter"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkCenter"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    serials_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStockSerialList"];
                };
            };
        };
    };
    serials_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockSerial"];
                "application/x-www-form-urlencoded": components["schemas"]["StockSerial"];
                "multipart/form-data": components["schemas"]["StockSerial"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockSerial"];
                };
            };
        };
    };
    serials_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this stock serial. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockSerial"];
                };
            };
        };
    };
    serials_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this stock serial. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockSerial"];
                "application/x-www-form-urlencoded": components["schemas"]["StockSerial"];
                "multipart/form-data": components["schemas"]["StockSerial"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockSerial"];
                };
            };
        };
    };
    serials_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this stock serial. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    serials_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this stock serial. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedStockSerial"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedStockSerial"];
                "multipart/form-data": components["schemas"]["PatchedStockSerial"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockSerial"];
                };
            };
        };
    };
    stocks_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStockList"];
                };
            };
        };
    };
    stocks_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this stock. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stock"];
                };
            };
        };
    };
    stocks_adjust_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Stock"];
                "application/x-www-form-urlencoded": components["schemas"]["Stock"];
                "multipart/form-data": components["schemas"]["Stock"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stock"];
                };
            };
        };
    };
    transactions_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStockTransactionList"];
                };
            };
        };
    };
    transactions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockTransaction"];
                "application/x-www-form-urlencoded": components["schemas"]["StockTransaction"];
                "multipart/form-data": components["schemas"]["StockTransaction"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockTransaction"];
                };
            };
        };
    };
    transactions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this stock transaction. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockTransaction"];
                };
            };
        };
    };
    transactions_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this stock transaction. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockTransaction"];
                "application/x-www-form-urlencoded": components["schemas"]["StockTransaction"];
                "multipart/form-data": components["schemas"]["StockTransaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockTransaction"];
                };
            };
        };
    };
    transactions_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this stock transaction. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    transactions_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this stock transaction. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedStockTransaction"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedStockTransaction"];
                "multipart/form-data": components["schemas"]["PatchedStockTransaction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockTransaction"];
                };
            };
        };
    };
    uom_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUOMConversionList"];
                };
            };
        };
    };
    uom_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UOMConversion"];
                "application/x-www-form-urlencoded": components["schemas"]["UOMConversion"];
                "multipart/form-data": components["schemas"]["UOMConversion"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UOMConversion"];
                };
            };
        };
    };
    uom_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this uom conversion. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UOMConversion"];
                };
            };
        };
    };
    uom_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this uom conversion. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UOMConversion"];
                "application/x-www-form-urlencoded": components["schemas"]["UOMConversion"];
                "multipart/form-data": components["schemas"]["UOMConversion"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UOMConversion"];
                };
            };
        };
    };
    uom_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this uom conversion. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uom_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this uom conversion. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUOMConversion"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUOMConversion"];
                "multipart/form-data": components["schemas"]["PatchedUOMConversion"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UOMConversion"];
                };
            };
        };
    };
    warehouses_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedWarehouseList"];
                };
            };
        };
    };
    warehouses_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Warehouse"];
                "application/x-www-form-urlencoded": components["schemas"]["Warehouse"];
                "multipart/form-data": components["schemas"]["Warehouse"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Warehouse"];
                };
            };
        };
    };
    warehouses_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this warehouse. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Warehouse"];
                };
            };
        };
    };
    warehouses_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this warehouse. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Warehouse"];
                "application/x-www-form-urlencoded": components["schemas"]["Warehouse"];
                "multipart/form-data": components["schemas"]["Warehouse"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Warehouse"];
                };
            };
        };
    };
    warehouses_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this warehouse. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    warehouses_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this warehouse. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedWarehouse"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedWarehouse"];
                "multipart/form-data": components["schemas"]["PatchedWarehouse"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Warehouse"];
                };
            };
        };
    };
}
