/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/notification/alerts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notification_alerts_list"];
        put?: never;
        post: operations["notification_alerts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification/alerts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notification_alerts_retrieve"];
        put: operations["notification_alerts_update"];
        post?: never;
        delete: operations["notification_alerts_destroy"];
        options?: never;
        head?: never;
        patch: operations["notification_alerts_partial_update"];
        trace?: never;
    };
    "/api/notification/alerts/{id}/read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["notification_alerts_read_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notification/alerts/read-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["notification_alerts_read_all_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Notification: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly user_id: string;
            /** Format: uuid */
            readonly company_uuid: string | null;
            title: string;
            message: string;
            type?: components["schemas"]["TypeEnum"];
            data?: unknown;
            link?: string | null;
            is_read?: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        PaginatedNotificationList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Notification"][];
        };
        PatchedNotification: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly user_id?: string;
            /** Format: uuid */
            readonly company_uuid?: string | null;
            title?: string;
            message?: string;
            type?: components["schemas"]["TypeEnum"];
            data?: unknown;
            link?: string | null;
            is_read?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
        };
        /**
         * @description * `info` - Info
         *     * `success` - Success
         *     * `warning` - Warning
         *     * `error` - Error
         * @enum {string}
         */
        TypeEnum: "info" | "success" | "warning" | "error";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    notification_alerts_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNotificationList"];
                };
            };
        };
    };
    notification_alerts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Notification"];
                "application/x-www-form-urlencoded": components["schemas"]["Notification"];
                "multipart/form-data": components["schemas"]["Notification"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notification_alerts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notification. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notification_alerts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notification. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Notification"];
                "application/x-www-form-urlencoded": components["schemas"]["Notification"];
                "multipart/form-data": components["schemas"]["Notification"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notification_alerts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notification. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notification_alerts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notification. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNotification"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNotification"];
                "multipart/form-data": components["schemas"]["PatchedNotification"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notification_alerts_read_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this notification. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Notification"];
                "application/x-www-form-urlencoded": components["schemas"]["Notification"];
                "multipart/form-data": components["schemas"]["Notification"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notification_alerts_read_all_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Notification"];
                "application/x-www-form-urlencoded": components["schemas"]["Notification"];
                "multipart/form-data": components["schemas"]["Notification"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
}
