/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/payments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["payments_list"];
        put?: never;
        post: operations["payments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["payments_retrieve"];
        put: operations["payments_update"];
        post?: never;
        delete: operations["payments_destroy"];
        options?: never;
        head?: never;
        patch: operations["payments_partial_update"];
        trace?: never;
    };
    "/api/payments/process/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["payments_process_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `card` - Credit/Debit Card
         *     * `cash` - Cash
         *     * `wallet` - Digital Wallet
         * @enum {string}
         */
        MethodEnum: "card" | "cash" | "wallet";
        PaginatedPaymentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Payment"][];
        };
        PatchedPayment: {
            /** Format: uuid */
            readonly id?: string;
            /**
             * Format: uuid
             * @description Reference to the Order in POS service
             */
            order_id?: string;
            /** Format: decimal */
            amount?: string;
            currency?: string;
            readonly status?: components["schemas"]["StatusEnum"];
            method?: components["schemas"]["MethodEnum"];
            readonly stripe_charge_id?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        Payment: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Format: uuid
             * @description Reference to the Order in POS service
             */
            order_id: string;
            /** Format: decimal */
            amount: string;
            currency?: string;
            readonly status: components["schemas"]["StatusEnum"];
            method?: components["schemas"]["MethodEnum"];
            readonly stripe_charge_id: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ProcessPayment: {
            /** Format: uuid */
            order_id: string;
            /** Format: decimal */
            amount: string;
            /** @default USD */
            currency: string;
            method: components["schemas"]["MethodEnum"];
            card_number?: string;
            expiry?: string;
            cvc?: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `completed` - Completed
         *     * `failed` - Failed
         *     * `refunded` - Refunded
         * @enum {string}
         */
        StatusEnum: "pending" | "completed" | "failed" | "refunded";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    payments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPaymentList"];
                };
            };
        };
    };
    payments_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Payment"];
                "application/x-www-form-urlencoded": components["schemas"]["Payment"];
                "multipart/form-data": components["schemas"]["Payment"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
        };
    };
    payments_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this payment. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
        };
    };
    payments_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this payment. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Payment"];
                "application/x-www-form-urlencoded": components["schemas"]["Payment"];
                "multipart/form-data": components["schemas"]["Payment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
        };
    };
    payments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this payment. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payments_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this payment. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPayment"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPayment"];
                "multipart/form-data": components["schemas"]["PatchedPayment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
        };
    };
    payments_process_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessPayment"];
                "application/x-www-form-urlencoded": components["schemas"]["ProcessPayment"];
                "multipart/form-data": components["schemas"]["ProcessPayment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
        };
    };
}
