/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/product/approvals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["approvals_list"];
        put?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        post: operations["approvals_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product/approvals/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["approvals_retrieve"];
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        put: operations["approvals_update"];
        post?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        delete: operations["approvals_destroy"];
        options?: never;
        head?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        patch: operations["approvals_partial_update"];
        trace?: never;
    };
    "/api/product/approvals/{id}/approve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        post: operations["approvals_approve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product/approvals/{id}/reject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        post: operations["approvals_reject_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product/attribute-sets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["attribute_sets_list"];
        put?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        post: operations["attribute_sets_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product/attribute-sets/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["attribute_sets_retrieve"];
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        put: operations["attribute_sets_update"];
        post?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        delete: operations["attribute_sets_destroy"];
        options?: never;
        head?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        patch: operations["attribute_sets_partial_update"];
        trace?: never;
    };
    "/api/product/attributes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["attributes_list"];
        put?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        post: operations["attributes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product/attributes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["attributes_retrieve"];
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        put: operations["attributes_update"];
        post?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        delete: operations["attributes_destroy"];
        options?: never;
        head?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        patch: operations["attributes_partial_update"];
        trace?: never;
    };
    "/api/product/brands/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["brands_list"];
        put?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        post: operations["brands_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product/brands/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["brands_retrieve"];
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        put: operations["brands_update"];
        post?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        delete: operations["brands_destroy"];
        options?: never;
        head?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        patch: operations["brands_partial_update"];
        trace?: never;
    };
    "/api/product/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["categories_list"];
        put?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        post: operations["categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product/categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["categories_retrieve"];
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        put: operations["categories_update"];
        post?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        delete: operations["categories_destroy"];
        options?: never;
        head?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        patch: operations["categories_partial_update"];
        trace?: never;
    };
    "/api/product/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["products_list"];
        put?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        post: operations["products_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product/products/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["products_retrieve"];
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        put: operations["products_update"];
        post?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        delete: operations["products_destroy"];
        options?: never;
        head?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        patch: operations["products_partial_update"];
        trace?: never;
    };
    "/api/product/units/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["units_list"];
        put?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        post: operations["units_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product/units/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["units_retrieve"];
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        put: operations["units_update"];
        post?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        delete: operations["units_destroy"];
        options?: never;
        head?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        patch: operations["units_partial_update"];
        trace?: never;
    };
    "/api/product/variants/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["variants_list"];
        put?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        post: operations["variants_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/product/variants/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        get: operations["variants_retrieve"];
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        put: operations["variants_update"];
        post?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        delete: operations["variants_destroy"];
        options?: never;
        head?: never;
        /** @description Base ViewSet to filter by company and auto-assign company on create. */
        patch: operations["variants_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApprovalRequest: {
            /** Format: uuid */
            readonly id: string;
            readonly product_name: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            /** Format: uuid */
            readonly requested_by: string;
            /** Format: uuid */
            readonly approved_by: string | null;
            /** @default pending */
            readonly status: components["schemas"]["StatusEnum"];
            comments?: string;
            /** Format: uuid */
            product: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `approved` - Approved
         *     * `rejected` - Rejected
         * @enum {string}
         */
        ApprovalStatusEnum: "pending" | "approved" | "rejected";
        Attribute: {
            /** Format: uuid */
            readonly id: string;
            readonly attribute_set_name: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            name: string;
            code: string;
            type?: components["schemas"]["TypeEnum"];
            options?: unknown;
            is_required?: boolean;
            /** Format: uuid */
            attribute_set: string;
        };
        AttributeSet: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            name: string;
        };
        Brand: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            name: string;
            /** Format: uri */
            logo?: string | null;
        };
        Category: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            name: string;
            icon?: string | null;
            description?: string | null;
            /** Format: uuid */
            parent?: string | null;
        };
        PatchedApprovalRequest: {
            /** Format: uuid */
            readonly id?: string;
            readonly product_name?: string;
            /** Format: uuid */
            readonly company_uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            is_deleted?: boolean;
            /** Format: uuid */
            readonly requested_by?: string;
            /** Format: uuid */
            readonly approved_by?: string | null;
            /** @default pending */
            readonly status: components["schemas"]["StatusEnum"];
            comments?: string;
            /** Format: uuid */
            product?: string;
        };
        PatchedAttribute: {
            /** Format: uuid */
            readonly id?: string;
            readonly attribute_set_name?: string;
            /** Format: uuid */
            readonly company_uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            is_deleted?: boolean;
            name?: string;
            code?: string;
            type?: components["schemas"]["TypeEnum"];
            options?: unknown;
            is_required?: boolean;
            /** Format: uuid */
            attribute_set?: string;
        };
        PatchedAttributeSet: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly company_uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            is_deleted?: boolean;
            name?: string;
        };
        PatchedBrand: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly company_uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            is_deleted?: boolean;
            name?: string;
            /** Format: uri */
            logo?: string | null;
        };
        PatchedCategory: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly company_uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            is_deleted?: boolean;
            name?: string;
            icon?: string | null;
            description?: string | null;
            /** Format: uuid */
            parent?: string | null;
        };
        PatchedProduct: {
            /** Format: uuid */
            readonly id?: string;
            readonly variants?: components["schemas"]["ProductVariant"][];
            readonly category_name?: string;
            readonly brand_name?: string;
            readonly unit_name?: string;
            readonly attribute_set_name?: string;
            /** Format: uuid */
            readonly company_uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            is_deleted?: boolean;
            name?: string;
            product_type?: components["schemas"]["ProductTypeEnum"];
            readonly approval_status?: components["schemas"]["ApprovalStatusEnum"];
            attributes?: unknown;
            tax_type?: string | null;
            tax_method?: components["schemas"]["TaxMethodEnum"];
            description?: string | null;
            /** Format: uri */
            thumbnail?: string | null;
            is_active?: boolean;
            /** Format: uuid */
            category?: string | null;
            /** Format: uuid */
            brand?: string | null;
            /** Format: uuid */
            unit?: string | null;
            /** Format: uuid */
            attribute_set?: string | null;
        };
        PatchedProductVariant: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly company_uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            is_deleted?: boolean;
            name?: string;
            readonly sku?: string;
            attributes?: unknown;
            /** Format: decimal */
            price?: string;
            /** Format: decimal */
            cost?: string;
            /** Format: decimal */
            quantity?: string;
            /** Format: decimal */
            alert_quantity?: string;
            /** Format: uuid */
            product?: string;
        };
        PatchedUnit: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly company_uuid?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
            is_deleted?: boolean;
            name?: string;
            short_name?: string;
            allow_decimal?: boolean;
        };
        Product: {
            /** Format: uuid */
            readonly id: string;
            readonly variants: components["schemas"]["ProductVariant"][];
            readonly category_name: string;
            readonly brand_name: string;
            readonly unit_name: string;
            readonly attribute_set_name: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            name: string;
            product_type?: components["schemas"]["ProductTypeEnum"];
            readonly approval_status: components["schemas"]["ApprovalStatusEnum"];
            attributes?: unknown;
            tax_type?: string | null;
            tax_method?: components["schemas"]["TaxMethodEnum"];
            description?: string | null;
            /** Format: uri */
            thumbnail?: string | null;
            is_active?: boolean;
            /** Format: uuid */
            category?: string | null;
            /** Format: uuid */
            brand?: string | null;
            /** Format: uuid */
            unit?: string | null;
            /** Format: uuid */
            attribute_set?: string | null;
        };
        /**
         * @description * `standard` - Standard Product
         *     * `service` - Service
         *     * `combo` - Combo
         *     * `consumable` - Consumable
         * @enum {string}
         */
        ProductTypeEnum: "standard" | "service" | "combo" | "consumable";
        ProductVariant: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            name: string;
            readonly sku: string;
            attributes?: unknown;
            /** Format: decimal */
            price?: string;
            /** Format: decimal */
            cost?: string;
            /** Format: decimal */
            quantity?: string;
            /** Format: decimal */
            alert_quantity?: string;
            /** Format: uuid */
            product: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `approved` - Approved
         *     * `rejected` - Rejected
         * @enum {string}
         */
        StatusEnum: "pending" | "approved" | "rejected";
        /**
         * @description * `exclusive` - Exclusive
         *     * `inclusive` - Inclusive
         * @enum {string}
         */
        TaxMethodEnum: "exclusive" | "inclusive";
        /**
         * @description * `text` - Text
         *     * `number` - Number
         *     * `date` - Date
         *     * `select` - Select
         *     * `boolean` - Yes/No
         * @enum {string}
         */
        TypeEnum: "text" | "number" | "date" | "select" | "boolean";
        Unit: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly company_uuid: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            is_deleted?: boolean;
            name: string;
            short_name: string;
            allow_decimal?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    approvals_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"][];
                };
            };
        };
    };
    approvals_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ApprovalRequest"];
                "multipart/form-data": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"];
                };
            };
        };
    };
    approvals_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this approval request. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"];
                };
            };
        };
    };
    approvals_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this approval request. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ApprovalRequest"];
                "multipart/form-data": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"];
                };
            };
        };
    };
    approvals_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this approval request. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approvals_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this approval request. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedApprovalRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedApprovalRequest"];
                "multipart/form-data": components["schemas"]["PatchedApprovalRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"];
                };
            };
        };
    };
    approvals_approve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this approval request. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ApprovalRequest"];
                "multipart/form-data": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"];
                };
            };
        };
    };
    approvals_reject_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this approval request. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ApprovalRequest"];
                "multipart/form-data": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRequest"];
                };
            };
        };
    };
    attribute_sets_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeSet"][];
                };
            };
        };
    };
    attribute_sets_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttributeSet"];
                "application/x-www-form-urlencoded": components["schemas"]["AttributeSet"];
                "multipart/form-data": components["schemas"]["AttributeSet"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeSet"];
                };
            };
        };
    };
    attribute_sets_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attribute set. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeSet"];
                };
            };
        };
    };
    attribute_sets_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attribute set. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttributeSet"];
                "application/x-www-form-urlencoded": components["schemas"]["AttributeSet"];
                "multipart/form-data": components["schemas"]["AttributeSet"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeSet"];
                };
            };
        };
    };
    attribute_sets_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attribute set. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    attribute_sets_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attribute set. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAttributeSet"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAttributeSet"];
                "multipart/form-data": components["schemas"]["PatchedAttributeSet"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeSet"];
                };
            };
        };
    };
    attributes_list: {
        parameters: {
            query?: {
                attribute_set?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `text` - Text
                 *     * `number` - Number
                 *     * `date` - Date
                 *     * `select` - Select
                 *     * `boolean` - Yes/No
                 */
                type?: "boolean" | "date" | "number" | "select" | "text";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attribute"][];
                };
            };
        };
    };
    attributes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Attribute"];
                "application/x-www-form-urlencoded": components["schemas"]["Attribute"];
                "multipart/form-data": components["schemas"]["Attribute"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attribute"];
                };
            };
        };
    };
    attributes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attribute. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attribute"];
                };
            };
        };
    };
    attributes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attribute. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Attribute"];
                "application/x-www-form-urlencoded": components["schemas"]["Attribute"];
                "multipart/form-data": components["schemas"]["Attribute"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attribute"];
                };
            };
        };
    };
    attributes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attribute. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    attributes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this attribute. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAttribute"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAttribute"];
                "multipart/form-data": components["schemas"]["PatchedAttribute"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attribute"];
                };
            };
        };
    };
    brands_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"][];
                };
            };
        };
    };
    brands_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Brand"];
                "application/x-www-form-urlencoded": components["schemas"]["Brand"];
                "multipart/form-data": components["schemas"]["Brand"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
        };
    };
    brands_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this brand. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
        };
    };
    brands_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this brand. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Brand"];
                "application/x-www-form-urlencoded": components["schemas"]["Brand"];
                "multipart/form-data": components["schemas"]["Brand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
        };
    };
    brands_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this brand. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    brands_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this brand. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBrand"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBrand"];
                "multipart/form-data": components["schemas"]["PatchedBrand"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
        };
    };
    categories_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
                "application/x-www-form-urlencoded": components["schemas"]["Category"];
                "multipart/form-data": components["schemas"]["Category"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
                "application/x-www-form-urlencoded": components["schemas"]["Category"];
                "multipart/form-data": components["schemas"]["Category"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCategory"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCategory"];
                "multipart/form-data": components["schemas"]["PatchedCategory"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    products_list: {
        parameters: {
            query?: {
                brand?: string;
                category?: string;
                is_active?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /**
                 * @description * `standard` - Standard Product
                 *     * `service` - Service
                 *     * `combo` - Combo
                 *     * `consumable` - Consumable
                 */
                product_type?: "combo" | "consumable" | "service" | "standard";
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
        };
    };
    products_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Product"];
                "application/x-www-form-urlencoded": components["schemas"]["Product"];
                "multipart/form-data": components["schemas"]["Product"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    products_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    products_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Product"];
                "application/x-www-form-urlencoded": components["schemas"]["Product"];
                "multipart/form-data": components["schemas"]["Product"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    products_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    products_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this product. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProduct"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProduct"];
                "multipart/form-data": components["schemas"]["PatchedProduct"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    units_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit"][];
                };
            };
        };
    };
    units_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Unit"];
                "application/x-www-form-urlencoded": components["schemas"]["Unit"];
                "multipart/form-data": components["schemas"]["Unit"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit"];
                };
            };
        };
    };
    units_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this unit. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit"];
                };
            };
        };
    };
    units_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this unit. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Unit"];
                "application/x-www-form-urlencoded": components["schemas"]["Unit"];
                "multipart/form-data": components["schemas"]["Unit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit"];
                };
            };
        };
    };
    units_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this unit. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    units_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this unit. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUnit"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUnit"];
                "multipart/form-data": components["schemas"]["PatchedUnit"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit"];
                };
            };
        };
    };
    variants_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVariant"][];
                };
            };
        };
    };
    variants_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductVariant"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductVariant"];
                "multipart/form-data": components["schemas"]["ProductVariant"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVariant"];
                };
            };
        };
    };
    variants_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this product variant. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVariant"];
                };
            };
        };
    };
    variants_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this product variant. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductVariant"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductVariant"];
                "multipart/form-data": components["schemas"]["ProductVariant"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVariant"];
                };
            };
        };
    };
    variants_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this product variant. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    variants_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this product variant. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProductVariant"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProductVariant"];
                "multipart/form-data": components["schemas"]["PatchedProductVariant"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVariant"];
                };
            };
        };
    };
}
