/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/promotion/coupons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["promotion_coupons_list"];
        put?: never;
        post: operations["promotion_coupons_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/promotion/coupons/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["promotion_coupons_retrieve"];
        put: operations["promotion_coupons_update"];
        post?: never;
        delete: operations["promotion_coupons_destroy"];
        options?: never;
        head?: never;
        patch: operations["promotion_coupons_partial_update"];
        trace?: never;
    };
    "/api/promotion/coupons/validate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["promotion_coupons_validate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Coupon: {
            /** Format: uuid */
            readonly id: string;
            code: string;
            discount_type?: components["schemas"]["DiscountTypeEnum"];
            /**
             * Format: decimal
             * @description Discount value (e.g. 10 for 10% or $10)
             */
            value: string;
            /** Format: decimal */
            min_purchase_amount?: string;
            /** Format: date-time */
            valid_from?: string;
            /** Format: date-time */
            valid_to?: string | null;
            active?: boolean;
            usage_limit?: number;
            readonly times_used: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `percent` - Percentage
         *     * `fixed` - Fixed Amount
         * @enum {string}
         */
        DiscountTypeEnum: "percent" | "fixed";
        PaginatedCouponList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Coupon"][];
        };
        PatchedCoupon: {
            /** Format: uuid */
            readonly id?: string;
            code?: string;
            discount_type?: components["schemas"]["DiscountTypeEnum"];
            /**
             * Format: decimal
             * @description Discount value (e.g. 10 for 10% or $10)
             */
            value?: string;
            /** Format: decimal */
            min_purchase_amount?: string;
            /** Format: date-time */
            valid_from?: string;
            /** Format: date-time */
            valid_to?: string | null;
            active?: boolean;
            usage_limit?: number;
            readonly times_used?: number;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        ValidateCoupon: {
            code: string;
            /** Format: decimal */
            amount: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    promotion_coupons_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCouponList"];
                };
            };
        };
    };
    promotion_coupons_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Coupon"];
                "application/x-www-form-urlencoded": components["schemas"]["Coupon"];
                "multipart/form-data": components["schemas"]["Coupon"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Coupon"];
                };
            };
        };
    };
    promotion_coupons_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Coupon"];
                };
            };
        };
    };
    promotion_coupons_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Coupon"];
                "application/x-www-form-urlencoded": components["schemas"]["Coupon"];
                "multipart/form-data": components["schemas"]["Coupon"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Coupon"];
                };
            };
        };
    };
    promotion_coupons_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    promotion_coupons_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCoupon"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCoupon"];
                "multipart/form-data": components["schemas"]["PatchedCoupon"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Coupon"];
                };
            };
        };
    };
    promotion_coupons_validate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateCoupon"];
                "application/x-www-form-urlencoded": components["schemas"]["ValidateCoupon"];
                "multipart/form-data": components["schemas"]["ValidateCoupon"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
