# Generated by Django 4.2 on 2025-12-23 08:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('branch_uuid', models.UUIDField(db_index=True)),
                ('environment_type', models.CharField(choices=[('RETAIL', 'Retail Store'), ('FACTORY', 'Factory Floor'), ('OFFICE', 'Head Office')], default='RETAIL', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisualCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('detected_items', models.JSONField(default=list)),
                ('is_converted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vision.camera')),
            ],
        ),
        migrations.CreateModel(
            name='PresenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(db_index=True, max_length=255)),
                ('person_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('VISITOR', 'Visitor'), ('UNAUTHORIZED', 'Unauthorized')], default='VISITOR', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_logs', to='vision.camera')),
            ],
        ),
        migrations.CreateModel(
            name='FootfallStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('entries', models.IntegerField(default=0)),
                ('exits', models.IntegerField(default=0)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footfall_stats', to='vision.camera')),
            ],
            options={
                'verbose_name_plural': 'Footfall stats',
                'unique_together': {('camera', 'timestamp')},
            },
        ),
    ]
