# Generated by Django 4.2 on 2025-12-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencelog',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entry'), ('OUT', 'Exit')], default='IN', max_length=10),
        ),
        migrations.AddField(
            model_name='visualcart',
            name='pos_terminal_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
