# Generated by Django 4.2 on 2025-12-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_presencelog_direction_visualcart_pos_terminal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='footfallstats',
            name='source',
            field=models.CharField(choices=[('AI', 'AI Vision'), ('MANUAL', 'Manual Entry')], default='AI', max_length=10),
        ),
        migrations.AddField(
            model_name='presencelog',
            name='source',
            field=models.CharField(choices=[('AI', 'AI Vision'), ('MANUAL', 'Manual Entry')], default='AI', max_length=10),
        ),
    ]
