# Generated by Django 4.2 on 2025-12-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0003_footfallstats_source_presencelog_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencelog',
            name='person_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('VISITOR', 'Visitor'), ('CUSTOMER', 'Customer'), ('UNAUTHORIZED', 'Unauthorized')], default='VISITOR', max_length=20),
        ),
    ]
