# Generated by Django 4.2.27 on 2025-12-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('INVENTORY', 'Inventory'), ('PRODUCTION', 'Production Order'), ('RECEIVING', 'Receiving')], max_length=20)),
                ('reference_uuid', models.UUIDField(db_index=True)),
                ('inspector_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QualityStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_uuid', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('criteria', models.TextField()),
                ('tolerance_min', models.FloatField(blank=True, null=True)),
                ('tolerance_max', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_value', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quality.inspection')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.qualitystandard')),
            ],
        ),
    ]
