# Generated by Django 4.2.27 on 2026-01-04 03:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='rework_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('REJECTED', 'Rejected'), ('REWORK', 'In Rework')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='quality.inspection')),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='defect_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quality.defectcategory'),
        ),
    ]
