# Generated by Django 4.2 on 2025-12-17 11:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('stock_level', 'Stock Level Change'), ('new_order', 'New Order'), ('payment_failed', 'Payment Failed'), ('shipment_status', 'Shipment Status Change'), ('scheduled', 'Scheduled Time')], max_length=50)),
                ('condition_field', models.CharField(blank=True, max_length=100, null=True)),
                ('condition_operator', models.CharField(default='==', max_length=20)),
                ('condition_value', models.CharField(blank=True, max_length=255, null=True)),
                ('action_type', models.CharField(choices=[('email', 'Send Email'), ('sms', 'Send SMS'), ('log', 'Log Alert'), ('webhook', 'Call Webhook'), ('create_task', 'Create Task')], max_length=50)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='success', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.automationrule')),
            ],
        ),
    ]
