# Generated by Django 4.2 on 2025-12-24 11:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_automationrule_company_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flow_data', models.JSONField(default=dict, help_text='JSON structure of steps and transitions')),
                ('company_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='automationrule',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='trigger_config',
            field=models.JSONField(blank=True, default=dict, help_text='Config for schedule (e.g. cron)'),
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_uuid', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('pending_approval', 'Pending Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('current_node_id', models.CharField(blank=True, max_length=100, null=True)),
                ('context_data', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='automation.workflow')),
            ],
        ),
    ]
