# Generated by Django 4.2.27 on 2025-12-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpsettings',
            name='default_from_email',
            field=models.CharField(max_length=255),
        ),
    ]
